### ISSUE TITLE
Processor count can be wrong (Mac without -threaded)

### ISSUE THREAD

**Issue by peti** [ndmitchell/shake#129]
Hi Neil, 

@jwiegley reported that Shake's test suite fails on Darwin. We have a build log at
http://hydra.nixos.org/build/11305822/log/raw that shows the failure. I hope this helps!

Peter

**Comment by ndmitchell** [comment]
Since Shake no longer supports GHC 7.2 I now use the function @kaoskorobase suggested. If someone with a Mac wants to modify https://github.com/ndmitchell/shake/blob/master/src/General/Extra.hs#L33 so it has a `doesDirectoryExist /proc` and if that returns `False` we run a system command and parse the output, then I'm happy with that. But it only affects Mac users who compile Shake build systems without threaded, so if no one wants to bother, I'll just close this ticket.

**Comment by ndmitchell** [comment]
In the absence of anyone stepping up to fix it, I'm closing the ticket.
