### ISSUE TITLE
Investigate oracle/cache relationship

### ISSUE THREAD

**Issue by ndmitchell** [ndmitchell/shake#185]
Discussing Oracle and Cache, it's clear there are multiple overlapping concerns. Effectively you want:
- A way of caching computation, sometimes transiently.
- A way of splitting a single value into multiple values.
- A way of storing something in the Shake database.

Currently `newCache` gives you transient computation, and `addOracle` gives you a way of storing in the database, plus a bit of splitting, but also brings `alwaysRerun` along for the ride - which is sometimes awful.

Maybe the type of addOracle and newCache combined looks something like:

```
addOracle' :: Action (q -> Action a) -> Rules ()
newCache' :: Action (q -> Action a) -> Rules (q -> Action a)
```

There's certainly something `Action (q -> Action a)` to `q -> Action a` in caching for splitting that probably wants surfacing a bit more directly. Using different names `new` vs `add` is probably a mistake as well.

**Comment by ezyang** [comment]
Correction: the output of oracles IS transiently cached (and persistently cached), since they are rules, and rules are only one once an invocation of Shake!

My thought was that everything should be a rule. I thus spent some time trying to work out how to encode caches as rules. I came to the conclusion that what we are missing is a few new states in the build system: `LazyLoaded`, `LazyChecking` and `LazyReady`. They form a graph like this:

```
LazyLoaded -> LazyChecking
LazyChecking -> Building
LazyChecking -> LazyReady
LazyReady -> Building
```

The basic idea is that a `LazyLoaded` rule is halfway between a `Missing` and a `Loaded` rule: if we ever actually directly NEED the value (via another Building key), we will need to build this key, but if no one ever actually directly needs this value, AND we otherwise could have skipped rebuilding the rule (because none of its dependencies changed), then it will always stay in the `LazyReady` stage and never actually get built.

This is kind of complicated, so I recommend just keeping caches, and maybe just supporting a more "rule-like" interface for them; i.e. instead of `newCache`, have `addCache` and `askCache`. `addCache` has slightly different semantics from `newCache`, in that you wouldn't be allowed to cache two different functions of the same type (that would make askCache different) but it would help you avoid having to "plumb" the cached functions around (the big benefit of the rule interface, despite the fact that it's terribly ambiguous.)

If you want an oracle that doesn't always rerun, we have a name for that: it's called a rule. But you could easily imagine a function `addRule`, which is implemented just like Oracles but without `alwaysRerun`. Then your only problem is what `storedValue` should be (with oracles, you can just return `Nothing` because you want it to rerun). But you stored the value already in the Shake database, so just make it accessible to `storedValue`! In https://github.com/ndmitchell/shake/issues/191#issuecomment-168112154 I sketched a simple extension to `storedValue` which would support this: just let a `storedValue` function say, "Whatever this value is, just get it from the Shake database!"

By the way, this is Haskell, not Plan 9, not everything should be a file. I definitely want my oracles to continue supporting arbitrary keys (less sold on the lack of key-value fundep) because this lets me encode richer structure than some sort of key. As far as I'm concerned, they don't look like files, so don't force them to be strings.

**Comment by ndmitchell** [comment]
I agree with all of what you said, including where you disagree with me :). I tend to view the Cache interface as more convenient, but oracles/rules must be statically resolvable by type so can't follow it. No reason not to provide versions of both for cache.

**Comment by ndmitchell** [comment]
I think with the refactoring of BuiltinRules, and the addition of `addOracleCache`, we now have everything in this ticket.
