### ISSUE TITLE
Target is not rebuild when dependencies are added

### ISSUE THREAD

**Issue by gdetrez** [ndmitchell/shake#210]
I'm not sure it's a bug but this confused me quite a lot.

If you have a  simple target like the following `bar`:

```haskell
want ["bar"]
"bar" %> \out -> do
    let deps = ["foo1"]
    need deps
    Stdout stdout <- cmd "cat" deps
    writeFileChanged out stdout

"foo*" %> \out -> writeFileChanged out out
```

when I run shake for the first time, both `foo1` and `bar` are created as expected. But if I then change it to

```haskell
...
    let deps = ["foo1", "foo2"]
...
```
in the rule for `bar` and run shake again, nothing is done although I expected `foo2` to be created and `bar` to be re-created.

**Comment by ndmitchell** [comment]
Unfortunately this is by design. I've explained all the details and workarounds [here](http://stackoverflow.com/a/14885431/160673). Basically in Haskell you don't have access to the source, and you can't see if the function has changed, and Shake doesn't rerun actions to check if they are up to date, so it can't be done nicely.

**Comment by gdetrez** [comment]
Thanks. I understand that shake cannot detect if a rule has been changed, as mentioned in the SO answer, but I think this is a bit different. I'm not only changing the rule but I'm also changing the dependency graph. I imagine shake could see that `foo2` does not exist and rebuild it, triggering a rebuilt of `bar` (apparently, this is what `make` does).

Or maybe shake could store the dependency graph of the last run and on the next run, compare it to the rebuilt dependency graph, and if any changes are detected in the list of dependencies for a target, it should be considered dirty (so you could handle *removing* a dependency, which `make` cannot do ;-)).

**Comment by gdetrez** [comment]
Oh... I just skimmed through your paper and I see that you cannot rebuild the graph without running the rule, which makes the suggestion above impossible... sorry!

**Comment by ndmitchell** [comment]
Yes, you're right, it's not possible. As a first approximation, users can write "really slow" stuff behind a rule, and even the process of resolving filenames to rules can be quite slow, since with `?>` you can supply an arbitrary predicate. To make rebuilding fast, Shake doesn't look at any of that, and just consults its trace of what happened last time, but that means it can't see the changes. If Shake had some custom-language, which wasn't Haskell (e.g. restricted, like Make) I could compare rules for textual similarity and trigger on that, but a full language makes that difficult or impossible.
