### ISSUE TITLE
Strange interaction between docker and shake after upgrading from shake version 0.8

### ISSUE THREAD

**Issue by skogsbaer** [ndmitchell/shake#217]
Hi Neil,

we have a problem with building our system with shake inside docker containers. shake rebuilds targets all the time, even if nothing changed. I think there is a bug in computing the timestamp of files. We are using ChangeModtime btw.

I think the problem is in src/Development/Shake/FileInfo.hs

There is conditional compilation going on, and my guess is that the part

#if MIN_VERSION_unix(2,6,0)
extractFileTime x = ceiling $ modificationTimeHiRes x * 1e4 -- precision of 0.1ms
#else

is wrong. I should not multiply by 1e4 but divide. 

In our case, the multiplication results in an overflow for the timestamp of the source file and than shake considers the source file to be more recent than the target file and recompiles everything.

I would simply use modificationTime instead of modificationTimeHiRes.

One more thing: while debugging all this, I noticed that the show instance of FileInfo subtracts 2 from the value, but the fileInfo function adds 3 to the value. Shouldn't these two be inverse?

Stefan

**Comment by ndmitchell** [comment]
Hi Stefan,

* The multiplication by 1e4 is correct. I get modification times as a floating point number of seconds. I multiply by 1e4 so the 0.1 ms values become Int and then use ceiling to grab the Int part. I expect some overflow, but as long as its deterministic, that's sufficient for Shake. I use the low bits to give a good timestamp - it's exceptionally rare files change year but not day at the same time.

* Can you use `-VVV` or shakeVerbosity=Diagnostic to get more information. In particular you should see lots of output, but one line should be the file, what it was recorded as, and what it appears as now. That should give you a clue as to what is going on.

* I suspect the show should add 3, and the comment above FileInfo should say 2 is special as well. Since it's only showing Int, and these Int's are pretty much a random selection of bits from a timestamp, without any external meaning, it doesn't really matter. But 2 isn't what I was aiming for, I'll audit more thoroughly tonight and check I'm not missing something, then change it.

Thanks, Neil

**Comment by ndmitchell** [comment]
Of course, there's an outside chance the overflow behaviour I'm relying on isn't well defined, and thus different inlinings produce slightly different roundings and that breaks my assumptions. Let me know if it seems to be that. Another possible cause would be Docker returning slightly different timestamps each time round - a print on the call with file/timestamp should show that.

**Comment by skogsbaer** [comment]
Here is the output of ls (for source and target file):

root@e9e329c9d1d6:/DociGateway-local/server# ls -l src/lib/Mgw/Util/Misc.hs
-rw-r--r-- 1 503 staff 11519 Feb 11 19:40 src/lib/Mgw/Util/Misc.hs
root@e9e329c9d1d6:/DociGateway-local/server# ls -l build/lib/Mgw/Util/Misc.f_o
-rw-r--r-- 1 root root 158088 Mar 18 09:28 build/lib/Mgw/Util/Misc.f_o

When playing around with ghci, you see that the extractFileTime function from shake does something odd:

Prelude System.Posix.Files.ByteString> hsStat <- getFileStatus "src/lib/Mgw/Util/Misc.hs"
Prelude System.Posix.Files.ByteString> foStat <- getFileStatus "build/lib/Mgw/Util/Misc.f_o"
Prelude System.Posix.Files.ByteString> modificationTimeHiRes hsStat
1423680015s
Prelude System.Posix.Files.ByteString> modificationTimeHiRes foStat
1426667311s
Prelude System.Posix.Files.ByteString Data.Word> let extractFileTime x = (ceiling $ modificationTimeHiRes x * 1e4)::Word32 -- "ported" from shake
Prelude System.Posix.Files.ByteString Data.Word> extractFileTime hsStat
3278531056
Prelude System.Posix.Files.ByteString Data.Word> extractFileTime foStat
3086719984

Here is some of shake's output when building build/lib/Mgw/Util/Misc.f_o:

% Chunk 368 [len 67] 0000018d000700000000000000187372632f6c69622f4d67772f5574696c2f4d6973632e6873010006c36a69f300002d020000000200000002000000020038345ae600 (Id 397,(src/lib/Mgw/Util/Misc.hs,Loaded (Result {result = File {mod=0xC36A69F1,size=0x2D00,digest=VAL}, built = Step 2, changed = Step 2, depends = [], execution = 4.3e-5, traces = []})))

% Chunk 1289 [len 75] 000005920007000000000000001b6275696c642f6c69622f4d67772f5574696c2f4d6973632e665f6f010006b7c79cc00002698b0000000200000002000000020101000006273b20902e00 (Id 1426,(build/lib/Mgw/Util/Misc.f_o,Loaded (Result {result = File {mod=0xB7C79CBE,size=0x26989,digest=VAL}, built = Step 2, changed = Step 2, depends = [[Id 1575]], execution = 2.45e-3, traces = []})))

As far as I understand the debugging output, the mod time of Misc.hs is larger than that of Misc.f_o, though that's not the case in reality.

I'm using the unix-2.6.0.1 package.

**Comment by skogsbaer** [comment]
I forgot to mention something important: we are using docker and shake 0.8.* for half a year without any such problems. The problem only occurred when upgrading shake to the latest version.

**Comment by ndmitchell** [comment]
OK, so given the sudden upgrade, it would be surprising if it wasn't an issue with Shake. The fact that the files change order when you truncate the bits isn't an issue - I only ever check if timestamps change, not that they are ordered. The log fragment shows what the files have been loaded at, can you also find the `valid` lines which say what the timestamps were now computed to. Something like:

    % valid False for output/basic/configure (File {mod=NEQ,size=NEQ,digest=NEQ})
    % valid True for output/basic/once.txt (File {mod=0x74EAFC53,size=0x1,digest=VAL
})
    % valid True for output/basic/zero.txt (File {mod=0x74E89AF3,size=0x1,digest=VAL
})

A few things occur to me:

* Try running with `--lint` first. If the issue is that timestamps are somehow unstable in your system that might show it up more directly.
* I note that Misc.f_o depends on Id 1575, while Misc.hs is Id 397. Likely that's irrelevant as there is an Id in between them that does the link (perhaps the .hi file, or a both node, if you are using `&%>`).
* The value for Misc.hs in your system matches what you computed. For Misc.f_o the value stored is B7C79CBE, but the computed value is b7fb9bef. Did you touch anything between taking those measurements and running the DB? The `valid` lines should give us all the information in one pass.

**Comment by skogsbaer** [comment]
I did another debugging session in a fresh docker container. Here is the outcome:

root@dfa53f382eef:/DociGateway-local/server# ghci -XOverloadedStrings
Prelude> import System.Posix.Files.ByteString
Prelude System.Posix.Files.ByteString> import Data.Word
Prelude System.Posix.Files.ByteString Data.Word> hsStat <- getFileStatus "src/lib/Mgw/Util/Misc.hs"
Prelude System.Posix.Files.ByteString Data.Word> foStat <- getFileStatus "build/lib/Mgw/Util/Misc.f_o"
Prelude System.Posix.Files.ByteString Data.Word> modificationTimeHiRes hsStat
1423680015s
Prelude System.Posix.Files.ByteString Data.Word> modificationTimeHiRes foStat
1426667311s
Prelude System.Posix.Files.ByteString Data.Word> let extractFileTime x = (ceiling $ modificationTimeHiRes x * 1e4)::Word32
Prelude System.Posix.Files.ByteString Data.Word> extractFileTime hsStat
3278531056 -- 0xC36A69F0
Prelude System.Posix.Files.ByteString Data.Word> extractFileTime foStat
3086719984 -- 0xB7FB9BF0

root@dfa53f382eef:/DociGateway-local/server# ls -l src/lib/Mgw/Util/Misc.hs build/lib/Mgw/Util/Misc.f_o
-rw-r--r-- 1 root root  158088 Mar 18 09:28 build/lib/Mgw/Util/Misc.f_o
-rw-r--r-- 1  503 staff  11519 Feb 11 19:40 src/lib/Mgw/Util/Misc.hs

root@dfa53f382eef:/DociGateway-local/server# ls -al build
total 440484
...
-rw-r--r--  1 root root   1992797 Mar 18 09:32 .shake.database

root@dfa53f382eef:/DociGateway-local/server# ./shake --shake-diagnostic --debug build/lib/Mgw/Util/Misc.f_o > shake.log 2>&1

Here is a summary of the shake.log file:

Starting build, targets: build/lib/Mgw/Util/Misc.f_o
Resolved targets: ["build/lib/Mgw/Util/Misc.f_o"]
% Chunk 31 [len 56] 0000002c000500000000000000187372632f6c69622f4d67772f5574696c2f4d6973632e68730100040100000002000000020037da1a9300 (Id 44,(doesFileExist src/lib/Mgw/Util/Misc.hs,Loaded (Result {result = True, built = Step 2, changed = Step 2, depends = [], execution =\
 2.6e-5, traces = []})))
% Chunk 368 [len 67] 0000018d000700000000000000187372632f6c69622f4d67772f5574696c2f4d6973632e6873010006c36a69f300002d020000000200000002000000020038345ae600 (Id 397,(src/lib/Mgw/Util/Misc.hs,Loaded (Result {result = File {mod=0xC36A69F1,size=0x2D00,digest=VAL}, built = S\
tep 2, changed = Step 2, depends = [], execution = 4.3e-5, traces = []})))
% Chunk 1287 [len 185] 0000062700090000000000000002000000000000001b6275696c642f6c69622f4d67772f5574696c2f4d6973632e665f6f000000000000001c6275696c642f6c69622f4d67772f5574696c2f4d6973632e665f68690100080000000000000002b7c79cc00002698b00000002b7c795b800002949000000020000000\
20000000205010000018b0100000336020000018d000004c7010000001501000004ba3f67e1330100000000000000066d792d676863402621f7405f420b (Id 1575,(build/lib/Mgw/Util/Misc.f_o build/lib/Mgw/Util/Misc.f_hi,Loaded (Result {result = Files {mod=0xB7C79CBE,size=0x26989,digest=VAL} {mod=0x\
B7C795B6,size=0x2947,digest=VAL}, built = Step 2, changed = Step 2, depends = [[Id 395],[Id 822],[Id 397,Id 1223],[Id 21],[Id 1210]], execution = 0.90578, traces = [Trace "my-ghc" 2.595823 3.488406]})))
% Chunk 1289 [len 75] 000005920007000000000000001b6275696c642f6c69622f4d67772f5574696c2f4d6973632e665f6f010006b7c79cc00002698b0000000200000002000000020101000006273b20902e00 (Id 1426,(build/lib/Mgw/Util/Misc.f_o,Loaded (Result {result = File {mod=0xB7C79CBE,size=0x26989,\
digest=VAL}, built = Step 2, changed = Step 2, depends = [[Id 1575]], execution = 2.45e-3, traces = []})))
% Chunk 1304 [len 76] 000005f20007000000000000001c6275696c642f6c69622f4d67772f5574696c2f4d6973632e665f6869010006b7c795b8000029490000000200000002000000020101000006273c9a75cd00 (Id 1522,(build/lib/Mgw/Util/Misc.f_hi,Loaded (Result {result = File {mod=0xB7C795B6,size=0x294\
7,digest=VAL}, built = Step 2, changed = Step 2, depends = [[Id 1575]], execution = 1.8855e-2, traces = []})))
% Chunk 5389 [len 185] 0000062700090000000000000002000000000000001b6275696c642f6c69622f4d67772f5574696c2f4d6973632e665f6f000000000000001c6275696c642f6c69622f4d67772f5574696c2f4d6973632e665f68690100080000000000000002b7ee19570002698b00000002b7c793a300002949000000020000000\
30000000305010000018b0100000336020000018d000004c7010000001501000004ba3f01e5190100000000000000066d792d6768633f708ebd3fb91b1e (Id 1575,(build/lib/Mgw/Util/Misc.f_o build/lib/Mgw/Util/Misc.f_hi,Loaded (Result {result = Files {mod=0xB7EE1955,size=0x26989,digest=VAL} {mod=0x\
B7C793A1,size=0x2947,digest=VAL}, built = Step 3, changed = Step 3, depends = [[Id 395],[Id 822],[Id 397,Id 1223],[Id 21],[Id 1210]], execution = 0.507402, traces = [Trace "my-ghc" 0.939678 1.44614]})))
% Chunk 5399 [len 76] 000005f20007000000000000001c6275696c642f6c69622f4d67772f5574696c2f4d6973632e665f6869010006b7c793a3000029490000000200000003000000030101000006273b2bf76a00 (Id 1522,(build/lib/Mgw/Util/Misc.f_hi,Loaded (Result {result = File {mod=0xB7C793A1,size=0x294\
7,digest=VAL}, built = Step 3, changed = Step 3, depends = [[Id 1575]], execution = 2.624e-3, traces = []})))
% Chunk 5404 [len 75] 000005920007000000000000001b6275696c642f6c69622f4d67772f5574696c2f4d6973632e665f6f010006b7ee19570002698b0000000200000003000000030101000006273a562bf100 (Id 1426,(build/lib/Mgw/Util/Misc.f_o,Loaded (Result {result = File {mod=0xB7EE1955,size=0x26989,\
digest=VAL}, built = Step 3, changed = Step 3, depends = [[Id 1575]], execution = 8.17e-4, traces = []})))
% Chunk 8264 [len 185] 0000062700090000000000000002000000000000001b6275696c642f6c69622f4d67772f5574696c2f4d6973632e665f6f000000000000001c6275696c642f6c69622f4d67772f5574696c2f4d6973632e665f68690100080000000000000002b7fbb8150002698b00000002b7c793a300002949000000020000000\
40000000405010000018b0100000336020000018d000004c7010000001501000004ba3f0020b40100000000000000066d792d6768633f38c8bd3f9c32ba (Id 1575,(build/lib/Mgw/Util/Misc.f_o build/lib/Mgw/Util/Misc.f_hi,Loaded (Result {result = Files {mod=0xB7FBB813,size=0x26989,digest=VAL} {mod=0x\
B7C793A1,size=0x2947,digest=VAL}, built = Step 4, changed = Step 4, depends = [[Id 395],[Id 822],[Id 397,Id 1223],[Id 21],[Id 1210]], execution = 0.500499, traces = [Trace "my-ghc" 0.721813 1.220298]})))
% Chunk 8265 [len 75] 000005920007000000000000001b6275696c642f6c69622f4d67772f5574696c2f4d6973632e665f6f010006b7fbb8150002698b0000000200000004000000040101000006273b437e6f00 (Id 1426,(build/lib/Mgw/Util/Misc.f_o,Loaded (Result {result = File {mod=0xB7FBB813,size=0x26989,\
digest=VAL}, built = Step 4, changed = Step 4, depends = [[Id 1575]], execution = 2.983e-3, traces = []})))
% Chunk 8266 [len 76] 000005f20007000000000000001c6275696c642f6c69622f4d67772f5574696c2f4d6973632e665f6869010006b7c793a3000029490000000200000004000000030101000006273bab92c000 (Id 1522,(build/lib/Mgw/Util/Misc.f_hi,Loaded (Result {result = File {mod=0xB7C793A1,size=0x294\
7,digest=VAL}, built = Step 4, changed = Step 3, depends = [[Id 1575]], execution = 5.236e-3, traces = []})))
% valid False for build/lib/Mgw/Util/Misc.f_o (File {mod=0xB7FBB813,size=0x26989,digest=VAL})
% Loaded -> Waiting, build/lib/Mgw/Util/Misc.f_o
# build/lib/Mgw/Util/Misc.f_o
% valid False for (build/lib/Mgw/Util/Misc.f_o build/lib/Mgw/Util/Misc.f_hi) (Files {mod=0xB7FBB813,size=0x26989,digest=VAL} {mod=0xB7C793A1,size=0x2947,digest=VAL})
% Loaded -> Waiting, build/lib/Mgw/Util/Misc.f_o build/lib/Mgw/Util/Misc.f_hi
# build/lib/Mgw/Util/Misc.f_o build/lib/Mgw/Util/Misc.f_hi
% valid True for src/lib/Mgw/Util/Misc.hs (File {mod=0xC36A69F1,size=0x2D00,digest=VAL})
% Loaded -> Ready, src/lib/Mgw/Util/Misc.hs
[DEBUG] Rule for compiling hs file, hs=src/lib/Mgw/Util/Misc.hs, depFile=build/lib/Mgw/Util/Misc.dep, pkgFile=build/lib/Mgw/Util/Misc.pkg, oDir=build/lib
src/lib/Mgw/Util/Misc.hs ==> build/lib/Mgw/Util/Misc.f_o
scripts/my-ghc -hide-all-packages -package-id HTF-0.12.2.2-c4266c43aec6695a5c240bcafc204137 -package-id base-4.6.0.1-8aa5d403c45ea59dcd2c39f123e27d57 -package-id containers-0.5.0.0-ab1dae9a94cd3cc84e7b2805636ebfa2 -package-id directory-1.2.0.1-91a788fd88acd7f149f0f10f5f\
1e23f2 -package-id filepath-1.3.0.1-b12cbe18566fe1532a1fda4c85e31cbe -package-id mtl-2.2.1-eda0a12427f66d975ce72a312c95b37a -package-id old-time-1.1.0.1-2f8ea093d0c7014780a8a5772f948883 -package-id time-1.4.0.1-10dc4804a19dc0000fab79908f1a9f50 -package-id unix-2.6.0.1-4\
f219f792083f70ec440ce406f12ce57 -isrc/lib -isrc/progs -ibuild/lib -ibuild/progs -ibuild/gen-hs -ibuild/gen-o -hisuf f_hi -osuf f_o -Werror -W -fwarn-unused-imports -fwarn-unused-binds -fwarn-unused-matches -fwarn-unused-do-bind -fwarn-wrong-do-bind -pgmPcpphs -optP--cpp\
 -rtsopts -threaded -funbox-strict-fields -O0 -outputdir build/lib -c src/lib/Mgw/Util/Misc.hs -o build/lib/Mgw/Util/Misc.f_o
# my-ghc (for build/lib/Mgw/Util/Misc.f_o build/lib/Mgw/Util/Misc.f_hi)
% Waiting -> Ready, build/lib/Mgw/Util/Misc.f_o build/lib/Mgw/Util/Misc.f_hi
% result (build/lib/Mgw/Util/Misc.f_o build/lib/Mgw/Util/Misc.f_hi) = (Files {mod=0xEF327FAD,size=0x26989,digest=VAL} {mod=0xB7C793A1,size=0x2947,digest=VAL})
% Waiting -> Ready, build/lib/Mgw/Util/Misc.f_o
% result build/lib/Mgw/Util/Misc.f_o = (File {mod=0xEF327FAD,size=0x26989,digest=VAL})
% Checking if build/lib/Mgw/Util/Misc.f_o is File {mod=0xEF327FAD,size=0x26989,digest=VAL}, passed
% Checking if build/lib/Mgw/Util/Misc.f_o build/lib/Mgw/Util/Misc.f_hi is Files {mod=0xEF327FAD,size=0x26989,digest=VAL} {mod=0xB7C793A1,size=0x2947,digest=VAL}, passed
% Checking if src/lib/Mgw/Util/Misc.hs is File {mod=0xC36A69F1,size=0x2D00,digest=VAL}, passed

Here is a link to the full shake.log file: https://dl.dropboxusercontent.com/u/10626736/shake-docker-problem.log

What has changed in shake in between 0.8 and now that could case such strange behavior under docker? Note that the problem only occurs the first time when entering the container. If I build the file again (in the same container), no recompilation is done:

root@dfa53f382eef:/DociGateway-local/server# ./shake build/lib/Mgw/Util/Misc.f_o
Starting build, targets: build/lib/Mgw/Util/Misc.f_o
Resolved targets: ["build/lib/Mgw/Util/Misc.f_o"]

**Comment by ndmitchell** [comment]
So the change which I'm getting increasingly sure is to blame is that previously Shake had 1 second-resolution timestamps, and now it has 0.1 millisecond resolution timestamps. Looking at the logs (thanks for those) I get:

* Shake ran and recorded a time of 0xB7FBB813 for Misc.f_o
* You restarted docker
* You manually sampled the time and it gave 0xB7FB9BF0

That equates to a 0.7s timestamp difference. Under the old Shake that might be considered "the same". Under the new Shake they won't.

Since the lint check succeeds that means that after a compile you still get given the exact same timestamp. My hypothesis is Docker is returning incorrect file times. Can you run the experiment:

* Create a file in Docker.
* Call `modificationTimeHiRes` on the file (not doing the weird Shake things, just the raw value).
* Get the time again.
* Restart docker.
* Get the time.
* Restart docker.
* Get the time.

If my guess is right, 1 and 2 will be the same time, 3 will be different, and then I have no idea if 4 will match 3 or be different again (that will give me more info though).

**Comment by ndmitchell** [comment]
Note that as a temporary workaround, changing to `ChangeModtimeAndDigest` would probably workaround the bug, as then you'd be relying on hashes not modtimes. Still interested in tracking it down properly though.

**Comment by skogsbaer** [comment]
Neil, thanks for your help. Just one quick question: what do you mean by "restarting docker"? Creating a new container from the same image? Or something else?

**Comment by skogsbaer** [comment]
So, did some more debugging. I couldn't verify your guess that docker returns inconsistent timestamps. But I noticed that the modification times inside a docker container never contain subseconds. The stat output always looks like this:

```
root@ac67985aa526:/DociGateway-local/server# stat build/lib/Mgw/Util/Misc.f_o
  File: ‘build/lib/Mgw/Util/Misc.f_o’
  Size: 158088    	Blocks: 312        IO Block: 4096   regular file
Device: 28h/40d	Inode: 389         Links: 1
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2015-03-21 09:19:01.287189223 +0100
Modify: 2015-03-21 09:15:18.000000000 +0100
Change: 2015-03-21 09:19:01.287189223 +0100
 Birth: -
```

Docker does a lot of magic, so I could imagine that there are situations where the mtime include subseconds, but I never encountered such a situation. I tested it during a docker build and also inside a docker container.

I then tried your suggestion with ChangeModtimeAndDigest.We are still using GHC 7.6, so I was hit by a GHC RTS bug I reported two years ago (https://ghc.haskell.org/trac/ghc/ticket/7646). I guess that computing the md5sum in shake causes this bug to appear. I our part of the build system, we are using special functions for reading files to work around this bug

I solution to the whole problem would be to add a flag to shake telling it not to use the subseconds of the mtime. Would this be an option for you?

**Comment by ndmitchell** [comment]
By restarting I meant shutting and reopenning the same Docker image. It does seem that Shake managed to record timestamps with some fractional seconds, since they're in the log. The fact that Shake doesn't rebuild after the first time also suggests it continued to return fractional seconds for some period of time. Perhaps the cache layer after writing out a file records the timestamps to more precision, but after that (once they are flushed to disk) it loses the subsecond part? I guess a single `ghci` in which you `writeFile` then immediately call `modificationTimeHiRes` might be interesting - if that gives fractional seconds then it would explain the issue.

Upgrading to 7.8 would probably be good, but we're still on 7.2, and also have nasty file reading functions to work around that bug...

If you compile Shake with the portable flag (`cabal configure --flags=portable`) I think that will only use second resolution. If it is more accurate than that, then I'm happy to change the meaning of the flag to ignore subseconds, since that would indeed give the most portable version.

**Comment by skogsbaer** [comment]
Ok, then I understood correctly what you meant with "shutdown". 

Your guess with the caching layer seems to to be good. It seems that docker looses timestamp precision when commiting a container's changes to a new image.

Inside docker container d33a797349c5:

```
root@d33a797349c5:/DociGateway-local/server# ghci -XOverloadedStrings
Prelude System.Posix.Files.ByteString> stat <- do writeFile "file.txt" "FOO"; getFileStatus "file.txt"
Prelude System.Posix.Files.ByteString> modificationTimeHiRes stat
1426949143.059797807s
root@d33a797349c5:/DociGateway-local/server# stat file.txt
  File: ‘file.txt’
  Size: 3         	Blocks: 8          IO Block: 4096   regular file
Device: 28h/40d	Inode: 1486        Links: 1
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2015-03-21 17:24:30.581088152 +0100
Modify: 2015-03-21 17:24:30.581088152 +0100
Change: 2015-03-21 17:24:30.581088152 +0100
Birth: -
```

Then commit the changes:

```
$ docker commit d33a797349c5
0a269c7307900268dcbd796d5316a8cef8ea0d9e78f55a5ea9c41f71cc28c131
```

Create a container from this new image:

```
$ docker run -i -t --rm 0a269c7307900268dcbd796d5316a8cef8ea0d9e78f55a5ea9c41f71cc28c131
root@d8b4c7d47d41:/DociGateway-local/server# stat file.txt
  File: ‘file.txt’
  Size: 3         	Blocks: 8          IO Block: 4096   regular file
Device: 28h/40d	Inode: 89          Links: 1
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2015-03-21 17:25:12.875520807 +0100
Modify: 2015-03-21 17:24:30.000000000 +0100
Change: 2015-03-21 17:25:12.875520807 +0100
Birth: -
```

I also tested with a patched version of shake, where timestamps do not have sub-seconds precision. With this version, everything is as with shake 0.8, that is there are no unnecessary rebuilds.

So, if shake could have an option that causes sub-seconds to be dropped, that would be great. For now, we are just using our patched version of shake, so there is no hurry.

**Comment by ndmitchell** [comment]
Did you try `cabal configure --flags=portable`?

**Comment by skogsbaer** [comment]
(way too late commenting on this issue)

Yes, it works with --flags=portable.

**Comment by ndmitchell** [comment]
Thanks for the info. Leaving it open for the moment - there's something fishy going on here, and I want to have a bit more think.

**Comment by ndmitchell** [comment]
I think a file system must have the invariant that modification time is correct and remains constant while things aren't being modified - and your Docker system seems not to, so (as far as I can tell) that's a bug in Docker or your particular Docker setup. Lots of people are using Shake with Docker successfully, so hopefully it's quite rare. There is the `portable` config flag workaround, and also you can use any of the `shakeChange` settings which also use digests, which is a generic workaround for any times of flakey modtime. If it happens to others I'll add it as an FAQ, and perhaps have some "test" mode, but otherwise I'll just ignore for now.
