### ISSUE TITLE
ChangeModtimeAndDigest doesn't work as documented

### ISSUE THREAD

**Issue by LukeHoersten** [ndmitchell/shake#218]
According to my understanding of [the documentation](http://hackage.haskell.org/package/shake-0.14.3/docs/Development-Shake.html#t:Change), if a target file's modification time has changed but its digest has not then `ChangeModtimeAndDigest` and `ChangeDigest` should have the same behavior: to not rerun the rule. This is not the case in 0.14.3. `(T && F) == F `

> ChangeModtimeAndDigest	
> A file is rebuilt if both its modification time and digest have changed. For efficiency reasons, the modification time is checked first, and if that has changed, the digest is checked.

Looking at [the relevant code for ChangeDigest](https://github.com/ndmitchell/shake/blob/3c474defd00174f366c8a1722cb865225c9ae5b2/src/Development/Shake/Rules/File.hs#L62), I don't see how `ChangeModtimeAndDigest` is supposed to work as documented. Maybe this was never implemented?

**Comment by ndmitchell** [comment]
Your understanding of what ChangeModtimeAndDigest is meant to do seems correct, but my reading of the code looks like it works. Let's run through the code path, simplifying away to assume `ChangeModtimeAndDigest` is selected:

    storedValue ShakeOptions{shakeChange=c} (FileQ x) = do
        Just (time, size) <- getFileInfo x
        hash <- unsafeInterleaveIO $ getFileHash x
        return $ Just $ FileA time size hash

OK, so we record the modtime, size of the file, and hash of the file. We then call `equalValue` between the old value and the new value.

    equalValue ShakeOptions{shakeChange=c} q (FileA x1 x2 x3) (FileA y1 y2 y3) =
        if x1 == y1 then EqualCheap
        else if x2 == y2 && x3 == y3 then EqualExpensive
        else NotEqual

Now we assume that the modtime has changed, but that the size and hash haven't:

    equalValue ShakeOptions{shakeChange=c} q (FileA x1 x2 x3) (FileA y1 y2 y3) =
        if False then EqualCheap
        else if True && True then EqualExpensive
        else NotEqual

So we get to `EqualExpensive`, which says that you don't need to rerun the rule, but that computing the quality was non-trivial (we had to read the file) so you should store an updated ModTime.

Does that make sense? Or did I just see what I wanted to see? I agree that using `_` as a fallthrough pattern instead of an explicit `ChangeModtimeAndDigest` was probably not ideal and does make it look like I didn't think about that case, when in reality I spent most time thinking about that case :).

**Comment by ndmitchell** [comment]
All this definitely isn't to say it works, merely that I can't spot an obvious error in the code you mentioned. A test case would be great to pin down what you are seeing.

**Comment by LukeHoersten** [comment]
Here's a little example:

```haskell
module Main where

import           Development.Shake (Action, Change (..), 
                                    ShakeOptions (..), cmd, liftIO, need,
                                    shakeArgs, shakeOptions, want, (%>), (~>))

main :: IO ()
main = shakeArgs shakeOpts $ do
    want ["node2.txt"]
    "leaf"      ~> leaf
    "node1.txt" %> node1
    "node2.txt" %> node2
  where
    shakeOpts = shakeOptions
        { shakeChange = ChangeModtimeAndDigest
        }

leaf :: Action ()
leaf = do
    liftIO $ print "RUNNING leaf"
    cmd "echo 'test'"

node1 :: FilePath -> Action ()
node1 file = do
    need ["leaf"]
    liftIO $ print "RUNNING node1"
    () <- cmd "touch" [file]
    cmd "echo 'test1' >>" [file]

node2 :: FilePath -> Action ()
node2 file = do
    need ["node1.txt"]
    liftIO $ print "RUNNING node2"
    () <- cmd "touch" [file]
    cmd "echo 'test2' >>" [file]
```

With `ChangeModtimeAndDigest`:
```
$ ./shake 
"RUNNING leaf"
# echo (for leaf)
'test'
"RUNNING node1"
# touch (for node1.txt)
# echo (for node1.txt)
'test1' >> node1.txt
"RUNNING node2"
# touch (for node2.txt)
# echo (for node2.txt)
'test2' >> node2.txt
Build completed in 0:01m
```

With `ChangeDigest`:
```
$ ./shake 
"RUNNING leaf"
# echo (for leaf)
'test'
"RUNNING node1"
# touch (for node1.txt)
# echo (for node1.txt)
'test1' >> node1.txt
Build completed in 0:01m
```

Run both twice to make sure you're getting a digest match but a different modtime. You can see here that `ChangeDigest` short circuits and doesn't run `node2.txt` as expected but `ChangeModtimeAndDigest` does run `node2.txt`.

**Comment by LukeHoersten** [comment]
Thanks for taking the time to file that. I've attached a minimal example to
illustrate the case.
https://github.com/ndmitchell/shake/issues/218#issuecomment-84706930

**Comment by ndmitchell** [comment]
Thanks for the test case, I'll have a proper look tomorrow (just heading to bed). I note you're running touch in the middle of the program, can you try running with `--lint` to check its not really a lint violation messing everything up? If not, then having `ChangeDigest` rebuild less than `ChangeModtimeAndDigest` does seem like a violation of some property you'd expect to hold.

**Comment by LukeHoersten** [comment]
Yes I ran this with lint. No violations. Touch is just for illustration.

**Comment by ndmitchell** [comment]
Thanks a lot for the test case, with that I was able to replicate the bug. I was using `==` instead of `equalValue` when figuring out if a file had changed during building (not at the start) so you were getting inconsistent results. I now use `equalValue` everywhere and it works. I've also turned your example into a test case.

**Comment by ndmitchell** [comment]
Turned out there were plenty of other issues in corner cases once I started using equalValue, all boiling down to treating missing hashes as equal. I've fixed them all now, and now treat a missing hash as never equal, but then use equalValue to ignore the hashes if they aren't active.

**Comment by LukeHoersten** [comment]
Thanks a lot Neil. I think I've been having this bug for some time. It was difficult to track down since I had complex builds. Once I started a new project I could more clearly see what was happening. Thanks for the fixes! This should result in less rebuilds for anyone using hashes!

**Comment by ndmitchell** [comment]
Yep, thanks for reporting it and reducing it for me, made it much more obvious to see it was entirely my fault. I'm hoping to make a release with this patch in the next few days.
