### ISSUE TITLE
make's "include" statement not supported?

### ISSUE THREAD

**Issue by jhedev** [ndmitchell/shake#238]
When running `shake` in a larger project that uses a bunch of Makefiles I get the following:

`shake: Invalid statement: include src/...`

Looks like `shake` does not support `include` currently?

**Comment by ndmitchell** [comment]
You are trying to use Shake as a direct replacement for `make`? There are lots of things that doesn't support, include statements being just one of them. Something like include is easy enough to add, but for any larger project there's likely to be something else that shake can't deal with too. None of these are insurmountable, but there hasn't been much call for using `shake` instead of `make`. What is the desire to use `shake` here?

(I should say, the Ninja interpreter in Shake is considered robust and fully featured, just not the Make one.)

**Comment by jhedev** [comment]
Yes, that's what I was trying. However, I was just playing around with `shake`. As I could not find any information about what make features are supported, I thought I should report it/ask  here.

I'm just kind of interested in Shake and playing around with it, so never mind :)

(Using `shake` and the Ninja files for the same project works quite well - good work!)

**Comment by ndmitchell** [comment]
The reason I don't really document which Make features are supported are because I doubt it will actually be useful to anyone in its current state. It was a prototype, and it shows you can interpret Makefiles, but also that there are a million features in Makefiles, some of which have difficult to pin down semantics, and every Makefile uses a few of the features.

**Comment by ndmitchell** [comment]
Since the make feature is discoverable, I should document it, just as someone to make it clear it's not expected to fully work.

**Comment by ndmitchell** [comment]
Documented in the FAQ.
