### ISSUE TITLE
MonadMask instance for Action

### ISSUE THREAD

**Issue by 3noch** [ndmitchell/shake#240]
`Action` is annoyingly restrictive in doing bracketed IO actions. How hard would it be to add an instance for `MonadMask` or less-preferably (IMHO) for `MonadBaseControl`?

**Comment by ndmitchell** [comment]
This is starting to become an FAQ, see https://github.com/ndmitchell/shake/issues/186 and https://github.com/ndmitchell/shake/issues/166, and a half written blog post with some of my earlier ideas: https://github.com/ndmitchell/blogs/blob/master/shake-exceptions.md. It basically boils down to two things:

* It's impossible, since `Action` is a continuation.
* It's undesirable, since then you could make choices depending on whether a rule succeeds or fails, whereas failure of a rule you depend on should result in you failing.

I do provide `actionFinally` and `actionOnException` as building blocks though, and `withTempFile` and `withTempDir`. And of course, if you are entirely in IO, then `liftIO` and `bracket` works fine. What was your example use case?

**Comment by 3noch** [comment]
Thanks for the clarification. In my context I need to wrap an action with a global file lock/unlock. It's certainly an undesirable situation, but for whatever reason the tooling we have does not support concurrent usage and does not protect itself from it. We're using a CI that where several builds can happen simultaneously.

However, that said, I took a look at `actionFinally` and I'm quite confident that will do what I need it to. So, instead of an issue, this should be a praise. Good work.

**Comment by ndmitchell** [comment]
Seems a shame the CI system can't do different builds at different times in different directories, or otherwise synchronize itself. Certainly Bake can (https://github.com/ndmitchell/bake) - although that's probably still not suitable for real humans just yet. Although Bake does have a super-robust file locking primitive (which auto-reaps if the calling process dies), so that may be worth stealing: https://github.com/ndmitchell/bake/blob/master/src/General/Extra.hs#L114

I'll close this ticket, and try and get round to finishing off the blog post sooner rather than later.

**Comment by 3noch** [comment]
@ndmitchell We're using Jenkins. It can build in different dirs, but our code-signing tooling is awful and doesn't support concurrent usage. So Jenkins is fine, but the signing will randomly clobber itself. We ended up using the `filelock` package because it has native Windows support without doing any `threadDelay`s. It also auto-unlocks on process death.

**Comment by 3noch** [comment]
@ndmitchell I noticed bake a while ago. I'd love to give a go some time.

**Comment by ndmitchell** [comment]
Ah, it seems the `filelock` might be a better alternative to what I'm doing - I'll add a note to switch in Bake in case that bit ever gives me problems.

**Comment by 3noch** [comment]
@ndmitchell It's only downside is that it doesn't have native support for a timeout, so you'd have to provide that yourself with `timeout` or similar.

**Comment by ndmitchell** [comment]
Yeah, I don't use timeout at the moment anyway, so not a problem - thanks for the pointer.

**Comment by 3noch** [comment]
Haskell has a thousand little gems.
