### ISSUE TITLE
Think about the GHC make2 build pattern

### ISSUE THREAD

**Issue by ndmitchell** [ndmitchell/shake#251]
GHC has roughly:

* `stage1/compiler.exe` depends on `src/Main.hs`
* `stage2/compiler.exe` depends on `src/Main.hs` and `stage1/compiler.exe`.

A full build is easy enough. Sometimes they want to switch to changing `src/Main.hs` and only rebuilding `stage2/compiler.exe`. Then they want to switch back and properly rebuild everything. How do you support that? So effectively you know `stage1/compiler.exe` is dirty, but don't worry about it for now.

cc @snowleopard who will want to know the answer.

**Comment by snowleopard** [comment]
At some point I was thinking about the following generic solution, which is probably an overkill in this case and may be very difficult to implement, but let me record it here anyway.

Is it possible to introduce OR-like dependencies (with the usual ones being AND-like)? For example, we might want to say that `Z` depends on `X` OR `Y` in the following sense: if you have either `X` or `Y` you know how to build `Z`. Perhaps, a simpler example would be: if I have either an `svg` image or an `eps` image, I could produce a `pdf` (I don't necessarily need both).

You first `need [X]` and try to rebuild it if necessary and if you fail you don't give up, but `need [Y]` instead.

With this functionality in place, we could have the following: `stage2/compiler.exe` depends on `stage1/compiler_shadow.exe` OR `stage1/compiler.exe`. The former has no dependencies on its own and we have no build rules for it, we simply create a shadow copy of `stage1/compiler.exe` when we like to avoid rebuilding the latter (and at the same time remove `stage1/compiler.exe` from our targets). When we want to initiate the full rebuild, we delete `stage1/compiler_shadow.exe` and the second branch of OR kicks in.

(I guess it's more like `orElse` rather than a typical OR.)

Does this make any sense?

**Comment by ndmitchell** [comment]
Or dependencies are frighteningly difficult to do. You might be able to put whether you are in `make2` mode in an oracle, and then you can use a shadow compiler. The hard bit is that when you switch back to not `make2` you don't invalid everything. I definitely need to think more...

**Comment by snowleopard** [comment]
Sorry for somewhat derailing the topic but I'd like to understand the difficulties of OR dependencies a bit better. Consider the following simple approach for the above example with `svg`/`eps` sources.
```haskell
"build/img/*.pdf" %> \out -> do
    let name = takeBaseName out
    srcs <- getDirectoryFiles "" $ [ "src/img" </> name <.> ext | ext <- ["svg", "eps"] ]
    when (null srcs) . error $ "No sources for " ++ out
    let src = head srcs -- potential caveat here
    need [src]
    if "//*.svg" ?== src then svg2pdf src else eps2pdf src 
```
The above code seems to be fairly robust and general (expensive `getDirectoryFiles` could be removed with help of `doesFileExist` but the result is less readable). 

The XOR case seems particularly straightforward and I don't see how the above can break. One caveat I see with the OR case is that if we once build using an `eps` source and later an `svg` source appears, we won't stick to the previous decision (`head srcs` will change its value) and will therefore initiate a possibly undesirable rebuild. However, I think it is possible to fix this by storing the previous decision in an oracle and reusing it when both sources are available.

Am I missing anything?

**Comment by ndmitchell** [comment]
I think if #436 was implemented you'd want `--skip=stage1/**`.

For the second point, I'd describe that as an `if` dependency, not an `or` dependency. You make a decision, and that forces you into one of two branches. For `or` dependency I mean where there are two dependencies and the build system has to make the choice which path to explore - that's difficult to model or implement.
