### ISSUE TITLE
Multi-target rule invoked unnecessarily

### ISSUE THREAD

**Issue by ppetr** [ndmitchell/shake#256]
A rule expressed using [`&%>`](https://hackage.haskell.org/package/shake-0.15.2/docs/Development-Shake.html#v:-38--37--62-) is run unnecessarily in certain cases. Consider the following dependency graph:

    b, c <- a
    d <- c

For building `d`, we need to build `c` from `a` and then `d` from `c`. However, if `b` is removed and _shake_ re-run again to build `d`, the first rule is still invoked, even though it's unnecessary, as `c` is up-to-date.
 
This can be demonstrated by the following example (expects file named `a` in the current directory):

```haskell

import Control.Monad
import Development.Shake
import Development.Shake.Command
import Development.Shake.FilePath
import Development.Shake.Util

main :: IO ()
main = shakeArgs shakeOptions{shakeFiles="_build"} $ do
    want ["_build/d"]

    ["_build/b", "_build/c"] &%>
      \[b, c] -> do
        let input = "a"
        need [input]
        command_ [Shell] "cat" [input, "|", "tee", b, "|", "tee", c]

    "_build/d" %> \t -> do
        let input = "_build/c"
        need [input]
        command_ [Shell] "cat" [input, ">", t]
```

**Comment by ppetr** [comment]
It seems that I have found a temporary workaround. The idea is to have multiple rules for each target, but wrap the action in [`newCache`](https://hackage.haskell.org/package/shake-0.15.2/docs/Development-Shake.html#v:newCache) first so that it's executed at most once:

```haskell
    ...

    act <- newCache $ \() -> do
        let input = "a"
            b = "_build/b"
            c = "_build/c"
        need [input]
        command_ [Shell] "cat" [input, "|", "tee", b, "|", "tee", c]

    forM_ ["_build/b", "_build/c"] (%> const (act ()))

    ...
```

**Comment by ndmitchell** [comment]
This is expected, because Shake introduces a hidden intermediate node `b+c`, so your dependencies really read:

    b+c <- a
    b <- b+c
    c <- b+c
    d <- c

After you remove `b` the `b+c` node is dirty so is rerun. The problem with your workaround (which effectively tweaks the dependency tree so that `b` and `c` are no longer tied) is that if you take your original dependencies and add:

   e <- b

Then if you rerun after `b` has been deleted, then you might build `d` (which doesn't rebuild `c`), then build `e` (which has to rebuild `c`, and thus rebuilds `b`). At the end of the build you now have `d` rebuilt with the old `c`, so the build is inconsistent.

In practice it's rare for the output of a rule to change. Is there something about your original example that makes it a problem?

**Comment by ppetr** [comment]
I see. Is this a fundamental limitation of the underlying system, or just the particular implementation? Would it be possible to implement `&%>` differently? From a semantic point of view, I'd say that it should be _rebuild just what's needed to produce the result_,. so the target for `b, c` in my example should be run only if either `b` is requested _and_ missing/outdated (and similarly for `c`).

To be more specific about my case: I have a lot of rules which produce 2 outputs: One part are results that I'm interested in (`b`s) and one part is something that's needed as the input for other rules (`c`s). The graph might look like this:
```
c0
 |\
c1 b1
 |\
c2 b2
 |
...
```
One rule builds `c1, b1` from `c0`, another rule builds `c2, b2` from `c1` etc.
At some point I want to remove some of the results which aren't needed any more (some `b`s, like `b1`), but Shake insists on rebuilding them even though they aren't needed (i.e. when I want to build `b2` and `c1` is up-to-date).

Thanks for pointing out the problem with the workaround. In my case this problem doesn't occur, as nothing depends further on `b`. I guess that it's a problem only if the output of the rule isn't pure in the sense that if it's run multiple times on the same input, the result (`c`) can differ, right?

**Comment by ndmitchell** [comment]
I think this is a fundamental limitation of any backward-driven build system with a rule that produces multiple arguments in one and can only run a rule once and seeks consistency. Unless you know in advance that you aren't going to need `b` (which is impossible in a monadic build system) then you can't chose to use a `c` that you might have to rebuild.

Why do you want to remove the `b`s? Disk space? Do the names of the `b`s keep changing? Deleting some build outputs, but not all, is something I've never had cause to do.

For your example, if you write `b1 b2` on the command line then your workaround might not be safe, but unless you deliberately do that, it's probably safe. Do you ever want to regenerate old `b`s that you have since deleted? If not, making `b1` depend on `c1`, but have no action, is probably the simplest thing that is guaranteed safe, and will blow up if you every try and demand `b1` and will never result in inconsistency.

**Comment by ppetr** [comment]
Thank you for the explanation, suggestions and help. Yes, disk space was the constraint, I used _shake_ for some data processing. The workaround worked for me, although next time I'll follow your suggestion to make it safer.

As this feature is probably impossible to implement for a backward-driven system, I'm closing the issue.
