### ISSUE TITLE
Packing a nice quasiquoter like interpolatedstring-perl6?

### ISSUE THREAD

**Issue by 3noch** [ndmitchell/shake#257]
`interpolatedstring-perl6` is super handy when you're doing a lot of string-splicing, which is very common in build scripts. Perhaps some form of this could be useful, maybe even one that has special quasi-quoters for paths and such.

**Comment by ndmitchell** [comment]
What exactly did you have in mind? I know @hvr has thought about quasi quoters for matching, and I think we decided it's quite close to the URL matching problem that all web servers have already solved in a variety of ways.

**Comment by ndmitchell** [comment]
There's certainly something interesting here, but I don't know what it looks like. I imagine something that smashes together file patterns, variable capture and something else. I'm sure the result will use Template Haskell, and since Template Haskell is a very heavy-weight dependency, it needs to live in a separate package. I leave it for someone else to put something together, but I'll happily link to the result.
