### ISSUE TITLE
newCache can't query itself

### ISSUE THREAD

**Issue by nh2** [ndmitchell/shake#270]
I noticed that I can't write a `Rule` like this using `newCache`:

```haskell
{-# LANGUAGE ScopedTypeVariables #-}
... = do -- :: Rules

  (getRecursiveIncludesOf :: FilePath -> [FilePath]) <- newCache $ \file -> do
    includes <- scanIncludesSingleFile file
    allIncludes <- traverse getRecursiveIncludesOf includes
    return allIncludes
```

because I'm in the body of the rule that defines `getRecursiveIncludesOf` (the name is not in scope inside the body).

However, I think for `newCache` this is sensible to have.

I wonder whether we should have a version of `newCache` that passes the cached function in.

--

Alternatively, I wonder if `Rules` should have a [`MonadFix`](http://hackage.haskell.org/package/base-4.8.0.0/docs/Control-Monad-Fix.html#t:MonadFix) instance! Then we could use `recursive do` notation (or `mdo`, see section *7.3.11. The recursive do-notation* in [the docs](https://downloads.haskell.org/~ghc/7.8.4/docs/html/users_guide/syntax-extns.html#7.3.8.%20The%20recursive%20do-notation)):

```haskell
{-# LANGUAGE RecursiveDo #-}
{-# LANGUAGE ScopedTypeVariables #-}
... = do -- :: Rules

  rec {
    getRecursiveIncludesOf <- newCache $ \file -> do
      includes <- scanIncludesSingleFile file
      allIncludes <- traverse getRecursiveIncludesOf includes
      return allIncludes
  }
```

It seems to me that it makes sense for `Rules` to have a `MonadFix` instance, since rules never run anything directly - they build a plan of things that can be built, and things inside (the `Action`s) are fundamentally allowed to ask for files built by the rules that implement the rule. The way around this (depending on a rule from inside the same rule) is usually: Because we use `Strings` in `need`!

The fact that `Rules` are order-independent supports this idea, and makes me think that it'd make sense for rules to be written in an `mdo` block in general (but that's a user's choice).

**Comment by nh2** [comment]
In fact, we can just `newtype Rules a = Rules (WriterT (SRules Action) IO a) deriving (..., MonadFix)`!

I added a PR, but let's first discuss whether this makes sense.

**Comment by ndmitchell** [comment]
My only concern with using `newCache` recursively is that if you have infinite recursion it's going to blow up unpleasantly (probably a blocked MVar message), compared to recursion in `need` which gives you nice polite errors and stack traces.

However, making it an instance of MonadFix is hardly advertising it, and as soon as you are using recursive do you are really signaling that you know way more than I do about semantics of recursive monads, so maybe that isn't a real problem. My temptation is to just merge this and see what happens. I'd also be tempted to shove MonadIO in at the same time, because it's useful - see #239 for the ticket thinking about that.

**Comment by ndmitchell** [comment]
Changelog updated. Deliberately not documenting, since those who are smart enough to make use of this correctly are probably smart enough to guess where it would be.
