### ISSUE TITLE
Shake not friendly to commercial builds

### ISSUE THREAD

**Issue by 3noch** [ndmitchell/shake#272]
I was not ready to find out that my build script is potentially vulnerable to licensing problems since it's on Windows: https://github.com/commercialhaskell/stack/issues/399

This might be something worth noting in a README or website!

**Comment by ndmitchell** [comment]
Is it really? To violate the license you'd have to ship a compiled Shake binary outside the organisation without source code. Since Shake is mostly used to build source code, you are presumably shipping the source code with it (or there's no point shipping the mechanism to build it), and thus you don't violate any issues. That all seems a bit unlikely. Or do you envisage other license concerns?

**Comment by 3noch** [comment]
You're right. I misunderstood the licensing requirements. This is good news!
