### ISSUE TITLE
Add shake to the shake report

### ISSUE THREAD

**Issue by knupfer** [ndmitchell/shake#311]
It would be great if the time spend on executing shake (the haskell side) would be part of the shake report (especially of the command plot).

My usecase is the following:
I've got a *huge* xml file which gets parsed and used for various build rules. I can't put the costly parsing into another haskell executable, that would disallow sharing the parsing for the various rules, but it makes the report having big holes.

**Comment by ndmitchell** [comment]
The reason I don't track the work the Haskell does is because I don't record start/end times as I start/stop working on a rule. A typical rule will suspend on every `need`, and very quickly resume. For large things like commands the overhead of tracking the pieces is relatively small, but for every interleave of every rule it would quickly get expensive.

However, it sounds like you might want [`traced`](https://hackage.haskell.org/package/shake/docs/Development-Shake.html#v:traced), which is what `cmd` calls under the hood. That way you can say: `traced "parse xml" (parser <$> readFile ...)`, perhaps with a `seq` to ensure the parser actually happens under the `traced`. Does that do what you want?

**Comment by knupfer** [comment]
That sounds good, I'll look into it the coming days...

**Comment by knupfer** [comment]
That worked like a charm, but now I can't figure out how I could trace an Action. I've got a writeFileChanged with some costly stuff which doesn't get tracked.

**Comment by ndmitchell** [comment]
You deliberately can't track the stuff in an Action. There are two ways to go with that - either evaluate the string strictly, e.g.:

     let xs = ... expensive thing here ...
     traced "expensive" $ evaluate $ rnf xs
     writeFileChanged filename xs

Or copy the definition of writeFileChanged and turn it into IO - the source is at https://github.com/ndmitchell/shake/blob/1068ea7d380c1575a97e7980dadffd3bb8cb7811/src/Development/Shake/Derived.hs#L153. It's only in Action for convenience, and could equally be in IO (I am still slightly considering putting it in MonadIO so it can be used in either).

**Comment by knupfer** [comment]
Ok, thank you very much. I'm closing this, it works very well on my side.
