### ISSUE TITLE
Add explicit user failure

### ISSUE THREAD

**Issue by quchen** [ndmitchell/shake#331]
I've been looking for a way to fail a build explicitly depending on some condition.

We can currently throw an `error` in `IO` via

```haskell
errorAction :: String -> Action a
errorAction = liftIO . throwIO . ErrorCall
```

but I feel like something like this should be part of the library already. Am I missing something?

(My use case is checking whether certain git repos are synchronized, and failing if they require manual inspection.)

**Comment by ndmitchell** [comment]
See the `fail` function in the `Monad`, which essentially corresponds to `errorAction`. Does that solve it for you?

**Comment by quchen** [comment]
The Action Monad is auto-derived over multiple stages, and ends up to be a Reader stack, which does not support `fail`. So calling `fail` resorts to throwing an error along the side channel that `error` provides. If it actually works this way, I think implementing `fail` explicitly via the IO-bound mechanism provided by `throwIO` would be a cleaner solution.

I'm not sure how artificial this case is, but since all bottoms are equal-ish, you wouldn't necessarily get the error you were throwing at some point. That's precisely what `throwIO` is there for if I understand it correctly.

**Comment by ndmitchell** [comment]
Using fail is perfectly robust, I have tests for that, so you have no need to worry. I agree that raising errors in IO is preferable, which is why Shake internally uses [`errorIO`](https://hackage.haskell.org/package/extra-1.4.2/docs/Control-Exception-Extra.html#v:errorIO) whenever it can.

Looking at the code, ReaderT properly implements fail in terms of its underlying fail, which is good. However, ContT doesn't, which I guess is a bug - I've raised it here: http://hub.darcs.net/ross/transformers/issue/10

So I could write my own `Monad` instance for `RAW` (the underlying Shake Monad), but then it becomes brittle if people remove or add fail/return/join to the Monad class, so I'm not too keen on doing that.

**Comment by quchen** [comment]
Alright, I can work with this, although I'd personally prefer having an explicit top-level "fail for Shake" while Monad.fail is as broken as it is right now. But that's not essential, so I'm going to close this issue. Thanks for your time!

**Comment by ndmitchell** [comment]
Since I guarantee `fail`, `error`, `throw` and `throwIO`, do feel free to use your custom `errorAction`. And if you can ever find any hole where the `fail` breaks, let me know. In the meantime, I'll try and get `fail` to work properly for `ContT` and then we can stick to failing in IO.
