### ISSUE TITLE
Add runAfter to API

### ISSUE THREAD

**Issue by quchen** [ndmitchell/shake#340]
When using Shake as a glue-y build system to gradually move out of a make-based system, it would be very useful to have the `runAfter` function available.

Right now, all we can do is `removeFilesAfter` (implemented in terms of `runAfter`), but there might be other actions to run after a build, such as calling `make clean` on a number of contained targets.

Is that a good idea? If not, why?

**Comment by ndmitchell** [comment]
Exposing runAfter isn't a particularly problem, but in general less functions is better. You can certainly implement runAfter outside of Shake - just do something like:

    main = do
        ref <- newIORef []
        shake ....
             phony "clean" $ do
                  modifyIORef ref (cmd "make clean" :)
         sequence_ =<< readIORef ref

So the question is whether it's important enough and generally useful enough to make a standard part of Shake, or if it's probably unique to your use case, in which case the above approach is probably sufficient. I've no real idea. What's the reason for wanting to do `make clean` after the build? The only real reason for having `removeFilesAfter` is so they can delete the `.shake/.database`, which is otherwise locked until the build completes - running `make clean` immediately might be fine.

**Comment by quchen** [comment]
> What's the reason for wanting to do make clean after the build?

The general case is that I'd like to pair a `clean` phony with other build rules, so that I can generate certain files and leave the system in the same state as it was before afterwards. When I accidentially pair the clean phony with another build target right now, I get very strange interferences, and the build fails for reasons not immediately obvious.

**Comment by ndmitchell** [comment]
Won't generating and then cleaning usually clean the generated files? If so, what's the purpose of generating the files? In my test suite I have a flag for "clean before", so I start from a known state, but I've never encountered a need for clean after before.

**Comment by quchen** [comment]
Cleaning should clean the generated files, but there may be other rules that do something with the generated files before the build finishes, such as moving them to a certain place.

Maybe I'm abusing Shake a bit to be not only a build system, but also a tool for shell scripting "of things with implicit data dependencies", and I think it does that job *very* well.

The small program I'm working on right now is a wrapper for a build system to compile the firmware for my [Infinity Ergodox keyboard](http://input.club/devices/infinity-ergodox), and the build system is a bit hard to understand. My Shake script now wraps the entire project, and when run, it moves the files to the appropriate (and a bit obscure) locations, then calls the other build system, and manages the generated files. My clean target should, among other things, call the clean target of the wrapped build system; but before cleaning, one might want to send the firmware to the keyboard on success, which would be a call to `./build --flash clean`.

**Comment by ndmitchell** [comment]
The `runAfter` API is all about running things after the Shake build has finished, mostly so you can clean up files that are currently locked by Shake itself. I think here you really want to say "do these two things, do this one after that" - but while Shake is still in control. You might also want to order clean before distclean or similar. Maybe there's a general design principle buried in there? But if it's hard to find, runAfter might be a simple stopgap, since it's no new power, and can certainly be useful.

Is your build script online somewhere? I'd be curious to take a look, and see if there's any other approach that might be better.

**Comment by quchen** [comment]
Here you go: https://github.com/quchen/ErgoDox
The main part of the build system is in [`Build/Main.hs`](https://github.com/quchen/ErgoDox/blob/master/Build/Main.hs).

**Comment by ndmitchell** [comment]
Thanks @quchen, I'll read through in detail later on in the week. One thing I immediately noticed is that you could replace `mkdir` with `createDirectoryIfMissing`, which means less shell, more Haskell, and might be easier.

**Comment by quchen** [comment]
Hey Neil, did you come to a conclusion? We should probably close this issue regardless of the outcome so it doesn't clutter the tracker.

**Comment by ndmitchell** [comment]
I did not - I've been super busy all over Christmas/New Year - it's still in the pile of things to look at. Don't worry about cluttering the bug tracker, I comb through it pretty regularly, so it won't stay forever.

**Comment by ndmitchell** [comment]
I added runAfter - I've now seen a couple of things that could be useful.

**Comment by quchen** [comment]
Cool, I had long forgotten about this ticket! :-)
