### ISSUE TITLE
Make Shake more applicative

### ISSUE THREAD

**Issue by ezyang** [ndmitchell/shake#343]
Reading through the documentation, I notice multiple admonitions that you should use fewer calls to need so that things can be built in parallel. We have a name for this pattern and it is called an applicative functor. Shake should be able to take advantage of code which does not use monadic bind and is applicative, to automatically coalesce calls to need.

**Comment by ndmitchell** [comment]
I'd argue that the Haxl project has a name for this pattern, but actually, Haskell doesn't - everyone expects `>>` and `<*>` to be roughly the same, and having different levels of parallelism between them is confusing, albeit mostly allowed by the semantics (but not super much when you have IO). I put some notes https://github.com/ndmitchell/shake/issues/269#issuecomment-115613931, but it probably deserves to be an FAQ.

**Comment by ezyang** [comment]
Yeah, I've noticed that Simon Marlow has been doing some work to support this in Haxl, e.g. applicative do: https://ghc.haskell.org/trac/ghc/wiki/ApplicativeDo

It is true that Haskell historically hasn't made a good distinction between these two operators. However, with AMP, I think that the standard library is getting a lot closer at supporting "applicative programming", and this is something that can be solved with user training. Simon Marlow might be able to say more about this.

**Comment by ndmitchell** [comment]
To my mind, anyone who writes two need operations on subsequent lines, assuming they will be fused together automagically, should probably write a comment stating their expectations. As a result, you might as well just write one need, and simplify the code and intentions.

That's not to say that if this becomes the expected semantics that I can't adjust in future - the Shake interface leaves room both ways. However, in my experience writing Shake builds, there's rarely a problem with insufficient parallelism and I don't often see excessive sequential needs which have real performance impact.

Tagging this ticket website, since I think it can be resolved by making a coherent argument and putting it in the FAQ. If that argument isn't coherent enough to convince people then we can revisit.

**Comment by ndmitchell** [comment]
I decided in the end my argument was that Shake is about writing and doing a few operations in each rule, Haxl is the opposite, which leads to the difference. Argument below and on the website:

In Shake, `need xs >> need ys` will build `xs` in parallel, then afterwards build `ys` in parallel. The same is true of `need xs *> need ys`, where `*>` is the applicative equivalent of `>>`. In contrast, [Haxl](https://hackage.haskell.org/package/haxl) will execute both arguments to `*>` in parallel. For Shake, you are encouraged to merge adjacent `need` operations (e.g. `need (xs++ys)`), and where that is not possible (e.g. when using `askOracle`) use `parallel` explicitly.

Shake _could_ follow the Haxl approach, but does not, mainly because they are targeting different problems. In Haxl, the operations are typically read-only, and any single step is likely to involve lots of operations. In contrast, with Shake the operations definitely change the file system, and there are typically only one or two per rule. Consequently, Shake opts for an explicit approach, rather than allow users to use `*>` (and then inevitably add a comment because its an unusual thing to do).
