### ISSUE TITLE
Should Development.Shake.Rule have a functional dependency?

### ISSUE THREAD

**Issue by ezyang** [ndmitchell/shake#345]
It's a multiparameter type class, and it can be easy to accidentally write some code which is ambiguous, e.g.:

```
polymorphicWant :: Rule k v => [k] -> Rules ()
polymorphicWant ks = action (void (apply ks))
```

```
GhcShake.hs:287:20:
    Could not deduce (Rule k v0)
    from the context (Rule k v)
      bound by the type signature for
                 polymorphicWant :: Rule k v => [k] -> Rules ()
      at GhcShake.hs:287:20-46
    The type variable ‘v0’ is ambiguous
    In the ambiguity check for the type signature for ‘polymorphicWant’:
      polymorphicWant :: forall k v. Rule k v => [k] -> Rules ()
    To defer the ambiguity check to use sites, enable AllowAmbiguousTypes
    In the type signature for ‘polymorphicWant’:
      polymorphicWant :: Rule k v => [k] -> Rules ()
```

It's seems like there should be at least a fundep from k to v.

**Comment by ndmitchell** [comment]
In fact I used to have such a dependency, but removed it. I want the dependency, but for the Oracle rule, I need to define:

    instance (ShakeValue q, ShakeValue a) => Rule (OracleQ q) (OracleA a) where

This can't be shown to be a functional dependency, since it's overlapping in some way. The way to convince GHC that was OK changed between versions, and in one version seemed to be buggy, so getting rid of the dependency was deemed the easy way out. I can try putting it back and see if it causes issues.

However, for https://github.com/ndmitchell/shake/issues/192, I might make mapping a single key to multiple values an expected and encouraged thing, so maybe adding it back is now a bad idea. Generally, I encourage everyone working at the apply layer to wrap it up to concrete types when exposing it outside that module, as I do with things like `need`.

For info, I'm away from computers Mon-Wed, so don't expect any responses early next week.

**Comment by ndmitchell** [comment]
It doesn't have a functional dependency for good reasons and by design. I recommend people always write a sugar function on top with concrete types.
