### ISSUE TITLE
phony API documentation is misleading

### ISSUE THREAD

**Issue by ezyang** [ndmitchell/shake#349]
> Declare a phony action -- an action that does not produce a file, and will be rerun in every execution that requires it.

What seems to be intended here is "execution" = "execution of Shake" (not execution of a rule which needs it), because otherwise it would contradict the lines below:

> You can demand phony rules using want / need. Phony actions are never executed more than once in a single build run.

Do you ever want to "need" a phony rule? The Makefile documentation says:

> A phony target should not be a prerequisite of a real target file; if it is, its recipe will be run every time make goes to update that file.

So it seems counterindicated. The next line in the API documentation makes this more confusing:

> Phony actions are intended to define command-line abbreviations.

For the USER, not the build system! If I want to abbreviate a command in my build system, I should write a Haskell function for it.

> If you need a phony action in a rule then every execution where that rule is required will rerun both the rule and the phony action.

It's very easy to misunderstand this statement to contradict the earlier one...

**Comment by ndmitchell** [comment]
Yes, this is a contradictory mess. The background is that it used to rebuild every single time you asked for it, but then it turned out a lot of people were doing need on a phony, so I gave it precise and semantics people wanted. It's still a terrible idea for anything but user-facing things though and generally people should be writing Haskell functions. Thanks for spotting.
