### ISSUE TITLE
A way to tell if a specific dependency has changed since the last time we ran the rule

### ISSUE THREAD

**Issue by ezyang** [ndmitchell/shake#350]
Yes, I know, this is terrible for hermetic builds, but GHC recompilation avoidance won't work otherwise. GHC needs to know if the source file has changed so it knows to unconditionally recompile the file; if the source file hasn't changed, GHC can do a more fine-grained check on the dependencies to see if recompilation is necessary.

Shake can't do this check, because it is at a much finer granularity than Shake can handle (it's not, "Did this .hi file change" but "did the ABI hash on this declaration change"). To teach Shake how to do GHC recompilation avoidance, you would have to (1) remove dependencies on hi files (otherwise you'll rebuild when any bit in an hi file changes), and (2) generate needs on *specific* declarations/export lists as GHC is parsing/renaming/typechecking a file. This is NOT impossible, but GHC would have to be refactored to do this.

**Comment by ndmitchell** [comment]
I imagine this is possible somehow, by abusing rules and IO, but not immediately sure how. I'll need to wait until I'm back at a computer and have a think.

**Comment by ndmitchell** [comment]
Can you sketch out a flow chart of the decisions you'd ideally like to be made? Something along the lines of:

* If the .hs file hasn't changed, skip.
* If the .hs file has changed, take the .hi file and the .hi of all immediate dependencies and run some GHC supplied function (that does the hash check or whatever - but the details are irrelevant if we can't break it apart - only the inputs/outputs matter - e.g. what goes in, does a single Eq'able hash come out).
* If the previous test returns False, then compile.

At a first guess, I think a two-step dependency structure of depending on the file, and then on the hash, should do it in some way. Shake has unchanging builds, which let you "abort" a recompilation (because a dependency didn't change), and I think that should let us have Shake encode the rules but GHC do the checking.

**Comment by ezyang** [comment]
So, here's how `ghc --make` works today:

1. If an `.hs` file has not changed, and all of its transitive dependencies (GHC unconditionally preprocesses and parses files to build an import graph every run of the compilation manager), we just skip compilation unconditionally. (This is referred to as "stable" in GhcMake.)

2. Otherwise, if an .hs file has not changed (so there is an existing, newer hi file) but it's not stable, we run the recompilation checker. The way this proceeds is we read in the old hi file, and then check if each recorded "usage" is consistent with the transitive set of interface files available to us. It is NOT the immediate dependencies; we may record a usage for something further down the tree, or even something external.

3. Otherwise, we compile.

Does your proposal work? If I understand correctly, you want to compute some sort of "environment hash", which combined with the source file are sufficient to tell if recompilation could change something.

I think this would work, but GHC doesn't generate any such hash presently. This is because you need to record enough information to be able to generate the hash in the first place (the usages), in which case it is much more straightforward to store the individual hashes and check them one-by-one.

But unchanging builds might give us a way out: instead of trying to agglomerating all of the hashes into a single hash, we could just have Shake track each of the individual dependency hashes. I thought this would not be possible to do (because I still need to need the actual interface file), but I think with unchanging builds, this concern no longer holds.

I must warn: there are a *lot* of these dependencies, so I don't know if atomizing in this way is actually a good idea. (We're also duplicating information which is stored in the hi file). I'm sure you'll know better!

**Comment by ezyang** [comment]
So, I attempted to implement this, but I couldn't figure out how to write the `Rule` instance for my hashes.

Suppose that every Haskell declaration has a "declaration hash" associated with it. I created a new data type to identify declarations, and wrote a Rule instance from declarations to hashes. The way I use this is, after compilation, I zip through the list of declarations Haskell used and run "action" to add them to the dependencies.

Unfortunately, I can't load the stored hash from `storedValue`, because Shake won't let me pass in some important variables to my function.

What should I do in this case? If I have `storedValue` return `Nothing` I get tons of lint errors (and it doesn't work); if I have `storedValue` return a bogus fingerprint, I don't get any lint errors but it still doesn't work.

**Comment by ezyang** [comment]
I think the answer is, don't use a rule, use an oracle!

**Comment by ezyang** [comment]
OK, I've successfully implemented this using oracles, so I'm going to close this.

**Comment by ndmitchell** [comment]
It sounds like your conclusion was:

* You need important extra information in `shakeExtra`, which you went and implemented.
* Rule is inherently confusing because `Nothing` should really be an ADT, which you also went and implemented.

So many thanks for this ticket, and the PR's that came from it!

**Comment by ezyang** [comment]
An important extra thing that arose while I was CRing my code: you DON'T want to use an Oracle for this; a persistent cache is better.
