### ISSUE TITLE
Transitive dependencies of the current rule

### ISSUE THREAD

**Issue by ezyang** [ndmitchell/shake#366]
When I write `ghc --make Main.hs`, the linking step knows that it must link:

1. All of the object files transitively depended on by `Main.hs`, and
2. All of the libraries that those object files may depend on (as recorded in their interface files).

I don't see any easy way to do this in Shake. In the manual, it is suggested that linking be done by scanning the source directory for all source files using `getDirectoryFiles`. I really don't want to do this, because I might not have even compiled all of the source files! I could scan the output directory, but I don't know if Shake removes files if their source disappears (would be very bad juju if it didn't.)

So, is there a way to get what a rule transitively depended on? Preferably lazily, because I may know how to prune the lookback at a certain point.

**Comment by ndmitchell** [comment]
The manual shows that you _can_ link everything in a directory using `getDirectoryFiles`, if that's your preferred convention. I think it is generally a terrible idea (hmm, I should probably write that in the manual!). Shake does not remove files after their source disappears, since generally removing people's files is a bad plan, but you can do it if you want: http://neilmitchell.blogspot.co.uk/2015/04/cleaning-stale-files-with-shake.html.

Fortunately, there's an easy way to do exactly what you want, using the technique from http://shakebuild.com/manual#generated-transitive-imports, and there's even an implementation of it at https://github.com/ndmitchell/shake/blob/master/src/Test/Self.hs#L43-L60. You basically store the one-level dependencies somewhere, and then take the transitive closure to do the transitive dependencies, and pass all that to the linker. I've used the same technique several times with great success.

**Comment by ezyang** [comment]
If I understand correctly, you successively compute the transitive closure of EACH dependency (the dep files are not one-level dependencies, but the full closure.) Why wasn't this done using a Rule whose return value is the list of dependencies?

**Comment by ndmitchell** [comment]
Each file has both a .dep and a .deps, the .dep is it's single-step dependencies and the .deps is it's transitive. It certainly could have been done as a rule, but putting it in a separate file makes it easier to view, using things like `cat`. You may well chose to do it as a rule.

**Comment by ezyang** [comment]
OK! I'm not really sure how the docs can be made clearer; I think what happened was I saw this section, but I saw it was for C and thought it wasn't applicable to my case. (Was looking for something which talked about linking.)

**Comment by ezyang** [comment]
I guess I'll do a file, because otherwise I have to make a new multi-output combinator which outputs both the deps and the output files.

**Comment by ndmitchell** [comment]
I'd certainly start with a file since it's easiest to debug. I wonder if there is some automatic pattern for generalising both files and other values at once... It certainly seems a shame to have to reimplement files for that.

In the new website I am pulling out an entire page covering this transitive pattern, so I have mentioned Haskell linking and will properly incorporate it into the text at some point.

**Comment by ezyang** [comment]
Just a comment: it turned out that GHC tracks the transitive closure of home modules already in the interface files, so I just read it out of the interface file directly.

**Comment by ezyang** [comment]
OK, closing.

**Comment by ndmitchell** [comment]
Ah, great, and hopefully the new website makes it clearer too, so all good there.
