### ISSUE TITLE
More descriptive types for Oracles

### ISSUE THREAD

**Issue by bgamari** [ndmitchell/shake#372]
The current incarnation of oracles seems to allow for an unfortunate amount of unsafety. In particular, it is painfully easy to use mismatched question/answer types. It seems like it would be quite straightforward to make this interface a bit safer,

``` haskell
-- | Implementers need to provide a `HasOracle` instance for their question type.
-- This requires that they provide the answer type as well as an action to
-- produce an answer.
class (ShakeValue q, ShakeValue (Answer q)) => HasOracle q where
    type Answer q
    answer :: q -> Action (Answer q)

-- | A constrained version of 'askOracle', ensuring that the answer type always
-- matches the question.
askOracle' :: (ShakeValue q, ShakeValue a, HasOracle q) => q -> Action (Answer q)
askOracle' = askOracle

-- | You need to register oracles just as you do currently
provideOracle :: (ShakeValue q, ShakeValue a) => proxy q -> Rule ()
provideOracle = addOracle answer
```

In principle you could also drop the requirement to register oracles, since you always have access to `answer` via the instance.

**Comment by snowleopard** [comment]
I stumbled upon the mismatch issue a couple of times, so checking this in compile time would be great.

If this allows us to drop the requirement to register oracles that would also be a big benefit.

**Comment by ndmitchell** [comment]
What you are describing is not that far off rules, rather than Oracles. In retrospect, I'm increasingly becoming convinced that Oracles were a way to work around the fact that defining your own rules were a pain. I hope to merge oracles and rules in a future version, and then they'll look closer to what you describe above (perhaps making it a multiparam type class rather than an associated type family - although they are pretty similar).

I don't think it will drop the registration requirement, because of internal details about how rules work and the requirement to preregister oracles so they can be checked without executing actions. Note that normal rules require registration, even file rules.

**Comment by bgamari** [comment]
Another (only somewhat related) point that I ran into while thinking about this is that it is sadly quite difficult to take a projection of an oracle. If I have an oracle which gives me an `a` and a function `a -> b` (where no information is "added" to the `a`, e.g. a field selector), ideally I would be able to depend just on the `b`.

**Comment by ezyang** [comment]
#345 is related: this bug suggests people seem to want the functional dependency between the input and output type.

**Comment by bgamari** [comment]
Indeed, in fact I think if we are to retain any notion like "oracle" the output type should be determined by the question type.

**Comment by ndmitchell** [comment]
With the newest version of Shake the `RuleResult` type function makes this rather easy.
