### ISSUE TITLE
Query for what changed which caused a rule to rebuild

### ISSUE THREAD

**Issue by ezyang** [ndmitchell/shake#381]
Is there any way to ask Shake to say what dependency changed which caused a rebuild? This feature would be a useful diagnostic when your build system is rebuilding too frequently.

**Comment by ezyang** [comment]
Poor man's way of doing this: run Shake in diagnostic mode with `-d`, and then grep for `(changed)`.

You could also look for `valid False` but you'll get a lot of `valid False` for Oracles (which always rerun every build) and then subsequently claim to be `(unchanged)`. So `(changed)` is better.

**Comment by ndmitchell** [comment]
The standard advice is to use the profiling. Do you want a way that doesn't use the profiling HTML pages? Or do you want it to be easier to see in the profile? I think adding a summary line into the profile saying "in the last execution most things rebuild because <foo> changed" would be helpful.

Because Shake has unchanging files, there's not really a first thing that changed, and you can have runs of `(changed)` things that get stopped by an `(unchanged)`, so I think the best way to compute an "answer" is to calculate which changed input was transitively responsible for most recompilation in the last run.

**Comment by ezyang** [comment]
OK, so to clarify this, the suggestion is to go to profile.html, select "Rule table", sort by "cost" (since that's the transitive time) and then look for entries for which unchanged is false?

**Comment by ndmitchell** [comment]
I'd recommend using the query `ancestorOf("interesting_thing") && leaf()`, then look for things which changed in run 0.

I think the profiling needs some extra modes in it which give more complete stories, some examples:

* "why did Foo.h rebuild" should give the full path from the leaf to Foo.h
* "what's the critical path" should give the critical path of a single-threaded built.

**Comment by ndmitchell** [comment]
Those two profiling questions have individual tickets: #414 for the critical path, and #148 for the what caused a rebuild, so closing this ticket.
