### ISSUE TITLE
low-level writeFileChanged copyFileChanged variants

### ISSUE THREAD

**Issue by jacereda** [ndmitchell/shake#422]
I'd like to have lower level variants of those returning `IO ()`, so I can use something like

    traced "dump" $ writeFileChanged' out contents

If you're OK with this change I can PR it.

**Comment by ndmitchell** [comment]
It's pretty sad that we then have `readFile'` being the Action version of `readFile` in IO, but `writeFileChanged'` being the IO version of `writeFileChanged` in Action. I don't particularly see any other way round that though...

**Comment by Mathnerd314** [comment]
Would ``traced' :: String -> Action a -> Action a`` work? The current ``traced`` just does ``liftIO act``.

**Comment by ndmitchell** [comment]
@Mathnerd314 - that seems far more sensible! Traced does two things, it prints messages and writes a profile entry. The reason its in IO is because it doesn't want to record time in which its building dependencies and thus not running the traced action. However, we can easily sidestep that by subtracting the change in localDiscount. It will make the profiling a bit worse if people do lots of needs inside a traced block, since we don't have a continuous block of time to color in on a pretty graph, but with a small warning on traced' that seems fine.

**Comment by ndmitchell** [comment]
I think there's broad consensus that everyone wants the non-Action functions to be MonadIO, not Action, which solves it for writeFileChanged, done as #58. With that change, is there still a desire to trace non-IO things?

**Comment by jacereda** [comment]
The only remaining bit would be `copyFileChanged`, would https://github.com/ndmitchell/shake/pull/444 be a solution for that? Then I could use it with something like plain `copyFile`.

**Comment by ndmitchell** [comment]
Yep, something along the lines of #444 seems reasonable.

**Comment by ndmitchell** [comment]
People can write this themselves on top of `fileEq` in the `extra` package if they need it so closing this ticket.
