### ISSUE TITLE
Have a way to trigger some `IO ()` for succcess/failure of build

### ISSUE THREAD

**Issue by jonathanjouty** [ndmitchell/shake#425]
I want my custom "CI" system to let GitHub or another service know when a build step starts, and then if it succeeds or fails.
I can imagine that it might not make sense to have this for every rule, so it could also be on a full build level.

The ways I can think of doing this:

1. Run actions I want to report with `notifyGitHub :: String -> Action a -> Action a` that does the work using `liftIO` and `actionOnException`
2. Set `shakeProgress` to something that will catch `ThreadKilled` and interrogates `IO Progress` to decide what to report
3. Some combination of `actionOnException` and `actionFinally` that I haven't quite figured out?

I'm currently using approach (1).
Had a go at (2) but always got `isFailed p == Nothing` in my exception handler :/
Welcome suggestions, I'm not sure there currently is the right mechanism to do this nicely?

**Comment by ndmitchell** [comment]
The function `shake`/`shakeArgs` will either complete cleanly, or if there is an exception, rethrow it. You can do:

    main = do
        print "Starting"
        res <- try $ shakeArgs shakeOptions myRules
        case res of
            Left e -> print "Failed"
            Right () -> print "Success"

Let me know if that doesn't work. I think the fact `shakeProgress` doesn't work could be fixed, although at the moment I think `isFailed` only returns `Just` if you have staunch mode on, and are thus continuing through a failure (and then the progress is interesting).

**Comment by jonathanjouty** [comment]
Thanks for the suggestion.
The problem with this is that `res` will not tell me anything interesting about the build. Namely, I won't know what build target caused the exception.

Regarding changing `shakeProgress`, is there a good reason for the current `isFailed` behaviour?

**Comment by ndmitchell** [comment]
In that example `e` will very probably be a value of type [`ShakeException`](https://hackage.haskell.org/package/shake-0.15.5/docs/Development-Shake.html#t:ShakeException), which will include the target, stack and error message.

The current `isFailed` behaviour is what happens if you have an async thread polling at 5s intervals and the exception stopping the polling - you don't get a final poll since that would be sync, not async. It's fixable though, as a special case, but arguably a quite useful special case.

**Comment by jonathanjouty** [comment]
I've been meaning to come back to this for a while...
I do not get `e :: ShakeException` in the example you provided.
Here's a minimal example based on yours:

```hs
main = do
  print "Starting..."
  shakeArgs shakeOptions myRules `catch` things
  where
    things (SomeException e) = hPutStrLn stderr $ show $ typeOf e
```

Where `myRules` fails, I always get `show $ typeOf e` as `ExitCode` and not `ShakeException`.

Here's *exactly* what I tried, for completeness: https://gist.github.com/jonathanjouty/a8b9f5cf19cea9ee4236aca7b390d791

**Comment by jonathanjouty** [comment]
I tried digging through the Shake sources to pinpoint this, but alas did not find anything.
*i.e.* I'm happy to investigate this if you point me in the right direction.

**Comment by ndmitchell** [comment]
Changing the example to:

```
main2 = do
  print "Starting..."
  withArgs ["--exception"] (shakeArgs shakeOptions myRules) `catch` things
  where
    things (SomeException e) = hPutStrLn stderr $ show $ typeOf e
```

Means it now prints out ShakeException. Looking through the code I can see where it does this, and it's a deliberate design decision. I suspect the reason is that I've already printed out the error in the body, so I don't want it printing again with the automatic printing the exception on failure handler in GHC. I'll see what I can do to make it work nicely with only one print of the exception, but this hack should let you get around the issue for now.

**Comment by Mathnerd314** [comment]
Also see #404.

**Comment by jonathanjouty** [comment]
This solves the issue for me, thanks!
