### ISSUE TITLE
cmd with forkIO

### ISSUE THREAD

**Issue by fakedrake** [ndmitchell/shake#459]
You may find this slightly unorthodox use of shake but here is what I could do with make that I can't do with shake: in shell 1 run `make run-server` in shell 2 `make build-all-js-files` reload browser. With shake that is impossible to my knowledge because `shake build-all-js-files` would throw something like `Shake failed to acquire a file lock on .shake/.shake.lock`.

Ideally I would like to be able to do

``` haskell
phony "run-server" $
  cmd ForkIO "python -m SimpleHTTPServer 8000" -- or something
```

So that I can still control (ie `C-c` to kill) the process and shake is happy that it did what I told it to and unlock.

Is this even possible in the current architecture of shake?

**Comment by ndmitchell** [comment]
Running two copies of Shake simultaneously on the same database is certainly not supported, and isn't going to work. There seem two options:

* Have `run-server` terminate immediately but leave the SimpleHTTPServer running. You couldn't use `cmd` like above since it blocks, but there are options you can give to sort that out. On Linux you get the problem of parents killing their children. Double forking fixes that, but starting to get confusing.

* Have `run-server` be handled outside of Shake - so if you see `run-server` in the command line arguments you spawn the server and don't even call into Shake. It's Haskell, so you have full control here.

I'd definitely go for option 2, or some variation on it.

If you are doing a long running `cmd` process you should pass `WithStderr False`, or Shake will indefinitely buffer everything on stderr, with an eventual memory exhaustion.

**Comment by fakedrake** [comment]
I tried this:

``` haskell
phony "liftIO $ do
  srvTid <- liftIO $ forkIO $ callCommand "python -m SimpleHTTPServer 8000"
  putLoud $ "Python server threadId: " ++ show srvTid
```

Which kind of works but it is detached from the haskell process which terminates immediately. I find it extremely strange that since it is a lightweight thread the parent process does not wait for it to finish... It will do for now though. Thank you. 

> If you are doing a long running cmd process you should pass WithStderr False, or Shake will indefinitely buffer everything on stderr, with an eventual memory exhaustion.

Great tip, thanks!

**Comment by ndmitchell** [comment]
Yes, Haskell has the model that when the main thread exits, everything gets taken down. I think the idea is that helper threads don't need to worry about termination, which can be a pain in a composable way.

**Comment by ndmitchell** [comment]
OK, considering this "solved" - let me know if you have any further problems with it. It is certainly possible to have two simultaneous copies of `make`, but not two of `shake` using the same database. That's known and expected, and rarely an issue, but can be worked around in the cases such as this.

**Comment by fakedrake** [comment]
Thank you again for being so responsive.
