### ISSUE TITLE
Phony actions named same as directories don't work anymore

### ISSUE THREAD

**Issue by mtolly** [ndmitchell/shake#465]
Sequel to my previous #405 :)

After upgrading stack snapshots, my phony actions throw errors if there is a directory with the same name. Tested and I narrowed it down to at least a regression between 0.15.5 and 0.15.9.

Clone https://github.com/mtolly/shake-phony-dir ; included are `stack.yaml` which uses 0.15.9 and `stack-good.yaml` which uses 0.15.5. I am on OS X if that matters; haven't tested on Windows.

```
$ stack build
...
$ stack exec shake-phony-dir -- foo
# ... builds foo/bar and foo/baz ...
$ stack exec shake-phony-dir -- foo
Build system error - expected a file, got a directory:
  Directory:  foo
Probably due to calling 'need' on a directory. Shake only permits 'need' on files.
```

```
$ stack build --stack-yaml=stack-good.yaml
...
$ stack exec --stack-yaml=stack-good.yaml shake-phony-dir -- foo
Build completed in 0:01m
$ stack exec --stack-yaml=stack-good.yaml shake-phony-dir -- foo
Build completed in 0:01m
```

Also, not sure if I should make a separate issue, but I noticed a while ago that this doesn't work, in either 0.15.5 or 0.15.9:

```
$ stack exec shake-phony-dir -- foo/
Error when running Shake build system:
* foo/
Error, file does not exist and no rule available:
  foo/
```

I know you mentioned in #405 that you are now normalizing slashes/backslashes in phonies; probably trailing slashes should be ignored as well, so `foo` == `foo/` just like in normal paths.

**Comment by ndmitchell** [comment]
Thanks for the high quality test case - I'll take a look later this evening.

**Comment by ndmitchell** [comment]
Fun bug! Very messy, and made doubly so since I've got some changes on top of the last release that I don't want to release yet - resulting in my first ever backport. Now fixed, and test cases added. Rough bug was that I was using a function that throws errors on directories (deliberately), but I even check it for phony before I happy to know that it's a phony rule. I'm planning to address that, but quick fix is make sure the "in advance" function tolerates directories.

As to the trailing `/`, I'm not sure normalising that away is a good idea - for files I don't normalise it away. Why not have your phony rules generate both `foo` and `foo/` variants?

**Comment by mtolly** [comment]
Wow, thanks for the quick fix!

> Why not have your phony rules generate both foo and foo/ variants?

Indeed, that sounds reasonable and appears to work great.
