### ISSUE TITLE
Command line flags don't correspond to shakeOptions

### ISSUE THREAD

**Issue by nkaretnikov** [ndmitchell/shake#470]
I'm using 0.15.10 and I don't see the analog of `-w` in `shakeOptions`. Similarly, `--verbose` doesn't accept an argument while `shakeVerbosity` does.
Also, see #49.

**Comment by ndmitchell** [comment]
Yes, it's not intended that all options are available in both ShakeOptions and on the command line - although it is the usual state of affairs, and #49 is an instance where it probably should be available in both.

You can get all the verbosity levels in shake using a combination of `--verbose` (which increases the verbosity) and `--quiet` (decrease verbosity). Use `--verbosity --verbosity` to increase by two levels.

Printing the directory (aka `-w`) is mostly there because of Make. I don't think it's a really useful feature, but if you want it, you can hardcode it in Shake yourself with `putStrLn =<< getCurrentDirectory`.

**Comment by ndmitchell** [comment]
I think `--verbose` and `--quiet` were the unclear ones (now help text is improved), while color is missing, but tracked at #49. If you see anything else you think would be useful to expose let me know.
