### ISSUE TITLE
More generic rule keys

### ISSUE THREAD

**Issue by nkaretnikov** [ndmitchell/shake#477]
Have you considered moving to a more generic keys rather than using `FilePath`s? Here's my usecase: I dynamically generate a bunch of rules based on the provided targets, and sometimes I want to build the same source file multiple times (with different flags). In the current setting, as I see it, the only way to achieve that is to employ stringly-typed programming: tag each output file with the target name (all as strings). This is not well-thought, but it would be cool to have predicates on something other than `FileType`s, for instance. Meaning that I should be able to plug in my custom type instead of `FileQ`, or something like that.

**Comment by ndmitchell** [comment]
In Shake all rule keys are fully polymorphic - see https://hackage.haskell.org/package/shake-0.15.10/docs/Development-Shake-Rule.html to define your own. However, if you want to build the same file each time with multiple different flags, they must go somewhere different on the file system each time, or they will overwrite each other - and thus you already need to make the file names unique somehow. There is a request to be able to reuse some of the FileA machinery in #388, but I'm not sure that would help here, because it very much assumes distinct keys.
