### ISSUE TITLE
Expose everything

### ISSUE THREAD

**Issue by nkaretnikov** [ndmitchell/shake#478]
While working on the build system, sometimes I make a change to my types, which leads to, say, overlapping rules being generated. I can fix this by fiddling with the rules, but that would obscure the purpose of the commit, making the diff hard to read and evaluate. It'd be great if I could use a dirty hack or two to filter out the rules with, say, `nub`, just to make the thing compile and build the project. Currently, I cannot do that because a lot of stuff is internal, to protect the innocent, I guess. How about exporting everything in `Internal` modules, including the value constructors (I miss certain instances sometimes)? Of course, I could patch the shake source itself, but that's an additional pain that I'd like to avoid.

**Comment by ndmitchell** [comment]
I'm against exporting `Internal` modules - it massively increases the API surface area people have to check (e.g. see `text` and `bytestring`), and anything `Internal` inevitably starts getting used. In your case of saying you want to `nub` the rules, where were you thinking of doing that using the `Internal` API? I think using `alternatives` might be sufficient for you. I prefer to address each potential use of `Internal` separately.

**Comment by nkaretnikov** [comment]
Okay, here's the issue I'm trying to deal with right now. As I mentioned, I want to generate rules based on the provided targets and source files. My code looks similar to this (haven't checked whether it compiles or not):
```Haskell
genRules :: [Src] -> [Target] -> Rules ()
genRules srcs targets =
  action $ do
    outs <- srcsToOuts srcs targets
    mconcat $ rule1 <$> targets
    mconcat $ (rule2 outs) <$> targets
    mconcat $ rule3 <$> outs
```

But it doesn't work because `Action` doesn't have a `Monoid` instance. Maybe it's a good thing since `action` is run on every execution. Okay, my next attempt is to work around this with an `MVar`:
```Haskell
genRules :: [Src] -> [Target] -> Rules ()
genRules srcs targets = do
  outsMVar <- liftIO $ newMVar []
  action $ do
    outs <- srcsToOuts srcs targets
    liftIO $ putMVar outsMVar outs
  outs <- liftIO $ takeMVar outsMVar
  unless (null outs) $ do
    mconcat $ rule1 <$> targets
    mconcat $ (rule2 outs) <$> targets
    mconcat $ rule3 <$> outs
```

This doesn't work either because the `Rules` type doesn't export its instances, including `MonadIO`.

Why am I even returning an `Action` from `srcsToOuts`? Well, it calls `getDirectoryFiles` somewhere, and I'd like to share this value instead of querying the filesystem in every rule. I hope I'm missing something because the only solutions I can think of at the moment are:
* Use `unsafePerformIO`, which I'm not sure how to reason about.
* Use a patched version of Shake.

Any ideas?

**Comment by Mathnerd314** [comment]
> the Rules type doesn't export its instances

All instances are exported; there's no way to hide them. But you need to import Control.Monad.IO.Class to have `liftIO` in scope.

It still doesn't work though, because the actions are run after any IO in the rules. There's an ML thread that seems similar though, you might see the solution there: https://groups.google.com/forum/?fromgroups#!topic/shake-build-system/DRIDIbtjWTs

**Comment by ndmitchell** [comment]
> Well, it calls getDirectoryFiles somewhere, and I'd like to share this value instead of querying the filesystem in every rule

If you call the tracked version `getDirectoryFiles` then it will only perform the IO at most once in any single run, everything else will simply point at it.

Another alternative would be to make `srcToOuts` in type `IO` rather than `Action` (doing some manual directory scanning), in which case it might be easier to integrate without needing to drop down to `Action`.

Note that the `action` is delayed until after the `Rules` have been executed, so the `takeMVar` program above most probably deadlocks.

**Comment by nkaretnikov** [comment]
@Mathnerd314, @ndmitchell: Thanks for your comments, I'll give it a try tomorrow!

**Comment by ndmitchell** [comment]
`liftIO` is even reexported by `Development.Shake`, so need to import anything else (although the module above certainly works too).

**Comment by nkaretnikov** [comment]
Okay, I think I know how I got confused. Importing `Control.Monad.IO.Class` doesn't work in 0.15.5 but works fine in the latest hackage version, so this is not an issue anymore. Regarding the `Action`, thanks for the heads up, @ndmitchell! It doesn't deadlock, but just returns an empty list, so no rules are being generated. I fixed that by moving to `getDirectoryFilesIO`. Thanks for the prompt help, as always! This issue can be closed unless I can convince you to export everything from the Internal modules. Or do you feel strongly about this?

**Comment by ndmitchell** [comment]
Oh, I thought you were using `newEmptyMVar` - yeah, adding no rules is the expected behaviour there.

I do feel pretty strongly about not exporting internal stuff, perhaps particularly so today, because I got burnt twice by "Internal" functions in ByteString that are now undocumented, change regularly, but are absolutely essential to get the right asymptotic performance!

I'm not totally averse to an "Internal" module, but only if it has a small subset of carefully chosen hacks into the middle of Shake that are dangerous and have an unstable API, but still let you do something useful that can't be done otherwise. I've not (yet) identified any suitable candidates to live in such an API.
