### ISSUE TITLE
Shake assumes that posix / UNIX file system times have high precision

### ISSUE THREAD

**Issue by cartazio** [ndmitchell/shake#482]
https://github.com/ndmitchell/shake/blob/41b55c471814b26c68b0346849643a9cfdc206f1/src/Development/Shake/Internal/FileInfo.hs#L172

Decided to investigate this on a hunch. On Mac OS X this assumption isn't true, see discussion at 
https://github.com/haskell/unix/pull/67

That said, OS X does have other higher Precision time tracking mechanisms. But I'm not sure if any are available for file systems :(
I can investigate if this is something that would be good for shake though.  

An alternative would be doing some sort of mapping that also tracks a file paired with its hash and some sort of time thing ? But that has slightly different semantics than modification time :(

Maybe one of the UNIX package mantainers know a not posix work around?

**Comment by Mathnerd314** [comment]
Shake uses high-precision time if available, but it doesn't assume anything about the actual time returned, beyond that it will be the same if the file is unchanged. So far this has led to one bug, #217, where filesystem timestamps are rounded in Docker on save/reload. As in that bug, you can use low-precision timestamps with --flags=portable. But it's not needed, since Mac timestamps are consistently low-resolution.

And Shake already has (several) hash+modtime modes, see the --digest-* / shakeChange family of options.

**Comment by cartazio** [comment]
Ok cool.  I'll dig into this more.

**Comment by ndmitchell** [comment]
Thanks @Mathnerd314 - that pretty much sums it up. High resolution timestamps are awesome, but their lack on Mac is well known. The test suite has to do some nasty dynamic timestamp resolution discovery to make sure it sleeps enough between touching files, but other than automated test suites, it doesn't affect much in practice, and if it ever does just use file hashes.
