### ISSUE TITLE
Recommended way to implement quicker action alternatives

### ISSUE THREAD

**Issue by expipiplus1** [ndmitchell/shake#502]
I have a build system which has a rule for producing `foo.out` from `code.in` and `data.in`. The process of compiling `foo.out` when `code.in` has changed, `slowCompile`, is very lengthy, however there does exist a process, `fastUpdate`, to *update* `foo.out` with a new `data.in` fairly quickly.

If `code.in` has changed then `slowCompile` must be run, using the new `code.in` and the existing `data.in`.

If `code.in` is unchanged but `data.in` is changed then `fastUpdate` can be run to produce a new `foo.out` from the old `foo.out` and the new `data.in`.

This is certainly possible in Shake with manual checks of the 'newness' of `data.in` and `code.in`. I'm wondering if there's a way of using the Shake machinery to do this though.

**Comment by ndmitchell** [comment]
Hmm, not that I can think of - the "difficult" bit is that you only want to run one of `fastUpdate` or `slowCompile`, never both. I'll have a further think.

**Comment by expipiplus1** [comment]
If Shake could expose something so an `Action` could find out why it's running then this might be nicer to do.

**Comment by matthiasgoergens** [comment]
I have a slightly similar use case with bulk-updates:

I have a command that makes targets [a, b] and commands to make [a] and [b] on their own.

If we need both [a] and [b] the bulk update is faster, but otherwise it's better not to update [a] when only [b] needs change and vice versa.

(My concrete use-cases are for having to install some dependency packages with apt-get and for some code-generation script that has a long initialisation time.)

**Comment by ndmitchell** [comment]
Thinking more, the general mechanism seems to be that you are writing a single rule that can produce multiple result files, and you want `needHasChanged` to ask if the `need` has changed since you last asked for it. You could imagine:

```
needHasChanged :: [FilePath] -> Action [Bool]
```

Certainly for advanced usage only, but I can see the merits. Unlike other `need` calls, this one is caller-context sensitive, so if two rules make the same `needHasChanged` call only one might report that it has changed, if both rules got run at different times.

**Comment by expipiplus1** [comment]
So there would be one action which branches between the slow and fast versions depending on the result of `needHashChanged`? If any of the slow causing inputs have changed then it does the slow thing, otherwise it does the fast thing.

**Comment by expipiplus1** [comment]
We've just thought of another use case for something like this. During our builds we run a tool which has a nontrivial startup time. It's lead to us batching up calls to this tool manually to amortise this cost. This is at the expense of finer dependency tracking.

**Comment by ndmitchell** [comment]
I think this is feasible in the current HEAD implementation of Shake, but I'm hoping to stabilise and push it out first, then go back to this in the 0.0.1 after that.

**Comment by ndmitchell** [comment]
I think all the issues on this ticket can be addressed by a combination of the `batch` function I just introduced (see 2b1e4729e4fab9845768096f8255fc42bcf2a24c for the docs) and `needHasChanged` in PR #539. Can anyone think of something missing?

**Comment by ndmitchell** [comment]
Closing - but if someone thinks of a new use case, shout and we can reopen.

**Comment by expipiplus1** [comment]
Great, looking forward to using the new functions!
