### ISSUE TITLE
Rules for `./file` not working

### ISSUE THREAD

**Issue by mtolly** [ndmitchell/shake#517]
On investigating strange errors in my build system it appears that rules for a file in the local directory given as `./file` are not working at all for me. Here's the sample program I tried:

```haskell
module Main where

import Development.Shake

main :: IO ()
main = shakeArgs shakeOptions $ do
  "./foo.txt" %> \out -> liftIO $ writeFile out "contents"
  "bar.txt" %> \out -> liftIO $ writeFile out "contents"
```

Getting the following result under LTS Haskell 7.12 (GHC 8.0.1, Shake 0.15.10) and 8.0 (GHC 8.0.2, Shake 0.15.11) as well as current `master` (ff8944743d5c6).

```
$ stack exec shake-bug -- foo.txt
Error when running Shake build system:
* foo.txt
Error, file does not exist and no rule available:
  foo.txt
CallStack (from HasCallStack):
  error, called at src/Development/Shake/Internal/Rules/File.hs:171:58 in shake-0.15.11-dG4i4UgsnKHpHjPMwn2lp:Development.Shake.Internal.Rules.File

$ stack exec shake-bug -- ./foo.txt
Error when running Shake build system:
* foo.txt
Error, file does not exist and no rule available:
  foo.txt
CallStack (from HasCallStack):
  error, called at src/Development/Shake/Internal/Rules/File.hs:171:58 in shake-0.15.11-dG4i4UgsnKHpHjPMwn2lp:Development.Shake.Internal.Rules.File

$ stack exec shake-bug -- bar.txt
Build completed in 0:01m
```

I am on macOS 10.11.6. I'll test with Linux shortly to see if I get the same result.

**Comment by ndmitchell** [comment]
That's what I expected. When you do a `need ["./foo.txt"]` or `need ["foo.txt"]` (which is what the command lines translate to), it always does a normalisation step on the file first, so always ends up asking for `foo.txt`. It is the case that `foo.txt` doesn't match the pattern `./foo.txt` since they are compared at the textual level, so you have no match.

One potential solution would be to do some normalisation on the `FilePattern` values which would cause them to match once more. However, the question then becomes if you normalise `..` in some way, which on a pattern with wildcards starts to have curious semantics.

**Comment by mtolly** [comment]
Hm, what I'm confused about is I'm (99%) certain this used to work. I haven't touched my code that triggered this in quite a while so I'm pretty sure it's been making a `./file` rule and then building `file` successfully until some recent point. (The superfluous `./` isn't hardcoded of course; it's the result of a relative path written in a potentially-in-another-directory file.)

But, I can certainly do that normalization myself before passing it to `%>`. Is it `System.FilePath.normalise` specifically that I should use to ensure it matches what Shake does?

**Comment by ndmitchell** [comment]
Ah! I suspect it's not a change in filepatterns, but a change in `</>`. At one point the filepath module was changed to insert `.` more readily. At another point Shake switched from mostly custom implementations to mostly reusing the filepath module. Either of those changes could show the behaviour you are reporting.

I normalise using https://hackage.haskell.org/package/shake-0.15.11/docs/Development-Shake-FilePath.html#v:normaliseEx beause `normalise` from `filepath` is pretty dodgy in a lot of corner cases. Mine also does `..` elimination - but that shouldn't be relevant to you (but not harmful).

My inclination is that Shake should ignore `./` in `FilePattern` because they arise so easily with `</>` and removing them is a pain. However, I don't think `FilePattern` should go anywhere near `..` as standard.

**Comment by mtolly** [comment]
Oh, that makes sense. That is indeed where the `.` comes from in the first place since I'm doing `takeDirectory someFile </> relativePathInThatFile`. And good to know about `normalizeEx`.

Also, here's a possibly related case, using an absolute path for a rule. (Which I haven't ever had a reason to do, but eh.)

```haskell
module Main where

import Development.Shake

main :: IO ()
main = shakeArgs shakeOptions $ do
  "/Users/mtolly/git/shake-bug/foo.txt" %> \out -> liftIO $ writeFile out "contents"
  "bar.txt" %> \out -> liftIO $ writeFile out "contents"
```

```
$ pwd
/Users/mtolly/git/shake-bug
$ stack exec shake-bug -- $(pwd)/foo.txt
Build completed in 0:01m
$ rm foo.txt
$ stack exec shake-bug -- foo.txt
Error when running Shake build system:
* foo.txt
Error, file does not exist and no rule available:
  foo.txt
CallStack (from HasCallStack):
  error, called at src/Development/Shake/Internal/Rules/File.hs:171:58 in shake-0.15.11-dG4i4UgsnKHpHjPMwn2lp:Development.Shake.Internal.Rules.File

$ stack exec shake-bug -- $(pwd)/bar.txt
Error when running Shake build system:
* /Users/mtolly/git/shake-bug/bar.txt
Error, file does not exist and no rule available:
  /Users/mtolly/git/shake-bug/bar.txt
CallStack (from HasCallStack):
  error, called at src/Development/Shake/Internal/Rules/File.hs:171:58 in shake-0.15.11-dG4i4UgsnKHpHjPMwn2lp:Development.Shake.Internal.Rules.File

$ stack exec shake-bug -- bar.txt
Build completed in 0:01m
```

This seems odd to me, that you have to match the absolute-or-relativeness of how the rule is defined when requesting a file to be built.

**Comment by ndmitchell** [comment]
Until quite late into the development of Shake, any absolute path was considered a bug. They still aren't a particularly good idea usually. But you're right, you must match relative/absolute sense of the path, so worth calling out somewhere in the docs.

**Comment by mtolly** [comment]
Cool, well `normaliseEx` fixed my problem. Thanks for the quick help :)

**Comment by ndmitchell** [comment]
Great. Let's keep this open for documenting the relative/absolute issue and normalising ./ in file pattern.

**Comment by ndmitchell** [comment]
I added the FAQ as part of #528. I made FilePattern assume `./` matches zero directories - so you have `*` for 1, `**` for 0-N and `.` for 0. The main thing is `</>` no longer causes issues so things will "just work" in more cases.
