### ISSUE TITLE
Clarify User vs Builtin rules

### ISSUE THREAD

**Issue by ndmitchell** [ndmitchell/shake#574]
See https://neilmitchell.blogspot.co.uk/2017/09/shake-016-revised-rule-definitions.html?showComment=1521767681664#c1857241005456990857 - concretely:

> I really don't understand what what builtin- and user rules are.
> What should I pass to 'addUserRule', what is the 'a' supposed to be?
> What is the idea behind UserRule? 
> And what are 'builtin rules'? 
> When do I need to add them, and why are they called 'built-in', if users can/have to add them ;) ?

Very good point, Builtin rules aren't built in.

**Comment by sheyll** [comment]
Thank you for creating the issue :)
I will try to figure out howto create a custom rule, and if I succeed I might post an example.

**Comment by ndmitchell** [comment]
That would be great. Are you able to say what the custom rule is? Generally I find it's quite rare that people actually need to use custom rules - often an oracle would be easier.

**Comment by sheyll** [comment]
I don't know if an oracle would be easier, because I am not really sure what the exact differences to using builtin- and user-rules are. 

I use shake as part of our internal build process, and that not only compiles stuff, but also uses generates VM images using a small library that wraps around command line tools like virsh and qemu-img. This library (that comes with a commandline executable) is called [b9](https://github.com/sheyll/b9-vm-image-builder).

That library has an internal image repository mechanism, such that one b9 project could create a VM image that is stored in the repository und other b9 projects can use it. 

The point of this repository is to reduce build time and disk space requirements. 

Build time is reduced by managing concurrent access to VM-images and serializing image creation and consumption, also build machines can share their repositories over the network (internally via rsync/ssh). Sharing images reduces build time because often it is faster to transfer VM-images than to rebuild them locally.

Disk space requirements are reduced by deleting obsolete versions of these VM images.

The Shake glue code I need, would lookup the exact version (aka build-id) of one kind of image using the B9 library modules to access the repository. The key is just a an image name and the value is some kind of random looking string that is uniquely generated during a build.

Some example code:

    import B9
           (ArtifactGenerator(..), SharedImage(..), SharedImageName(..),
            SharedImageBuildId(..), siName, siDate, siBuildId)
    import qualified B9
    
    (stuff omitted ...)
    
    lookupCachedSharedImage
      :: MonadIO m => SharedImageName -> m (Maybe SharedImageBuildIdA)
    lookupCachedSharedImage n = do
      cfgParser <- B9.readB9Config Nothing
      liftIO $ B9.run cfgParser B9.defaultB9Config go
     where
      go =
        extractNewestImageFromResults
          <$> B9.lookupSharedImages isAvailableOnLocalHost hasTheDesiredName
       where
        extractNewestImageFromResults = listToMaybe . map answer . take 1 . reverse . map snd
        isAvailableOnLocalHost = (B9.Cache ==)
        answer (B9.SharedImage _ _ (B9.SharedImageBuildId i) _ _) =
          SharedImageBuildIdA i
        hasTheDesiredName (B9.SharedImage n' _ _ _ _) = n == n'

**Comment by ndmitchell** [comment]
I just released shake 0.16.4 which provides newOracleCache. With that you can define a rule that maps between a SharedImageName and a SharedImageBuildId - looking it up if it exists, and building it otherwise. I'm going to claim (but am not yet convinced myself yet...) that all rules could be defined on top of newOracleCache, and that the builtin rule mechanism is just a way of making things more efficient (but unlikely to matter in most cases).

Can I suggest you try `newOracleCache` and report bugs if it is insufficient?

**Comment by sheyll** [comment]
I just finished up a version with an integration based on 'addUserRule' and 'addBuiltinRule', [see B9.Shake.SharedImageRules](https://github.com/sheyll/b9-vm-image-builder/blob/0.5/src/lib/B9/Shake/SharedImageRules.hs).

I would proceed to write up a small blog article, using this or the next feature I am going to add, as an example of how to develop custom shake stuff.

I can also try 'newOracleCache' with the afore mentioned other shake integration in line for integration into the b9 code base.

**Comment by ndmitchell** [comment]
See also https://www.reddit.com/r/haskell/comments/8amdov/i_wrote_a_short_piece_on_three_important_concepts/ for more background.

**Comment by sheyll** [comment]
Yeah, that was very helpful thanks!

**Comment by ndmitchell** [comment]
I wrote a lot of details at https://github.com/ndmitchell/shake/blob/master/src/Development/Shake/Rule.hs - does that clarify things? To see more completely, check out the repo, generate Haddock, and browse to Development.Shake.Rule.

**Comment by ndmitchell** [comment]
Treating this as closed, but please reopen if there are further clarifications required.
