### ISSUE TITLE
Description in shake.cabal seems incorrect - no "Examples" directory

### ISSUE THREAD

**Issue by phlummox** [ndmitchell/shake#576]
For version 0.16.3 and HEAD, the "description:" field in [`shake.cabal`](https://hackage.haskell.org/package/shake-0.16.3/src/shake.cabal) states that "Further examples are included in the Cabal tarball, under the `Examples` directory". However, there doesn't seem to be any such directory, either in the Cabal tarball or the git repository, so far as I can see - should the description be corrected?

**Comment by ndmitchell** [comment]
Thanks for pointing that out! Historical reasons - when Shake was first written it had no real examples, but a few test cases in Examples were about the best you could do. Now it's got a real user manual with real examples which people should follow instead of the test suite which is a bit funky (since it's purpose is testing). I've removed that.

**Comment by phlummox** [comment]
No worries :)
