### ISSUE TITLE
incompatible with HLint

### ISSUE THREAD

**Issue by mcandre** [ndmitchell/shake#578]
If Cabal installs HLint after shake, it A) requires `--force-reinstalls` and B) breaks shake, causing import errors when I run `shake`. Could shake align its dependency tree closer to HLint (or go the other direction and submit pull requests to align HLint's dependency tree with shake), so that these two packages integrate better in Cabal?

As a workaround, I am installing HLint first, and then shake second, to ensure that `shake` continues to work.

**Comment by ndmitchell** [comment]
Thanks for the report @mcandre. Do you know what dependency causes the problem? Since neither HLint or Shake have upper bounds that conflict, if you do a `cabal update` first the solver _should_ have picked identical bounds for both. FWIW, on my machine I have both Shake and HLint installed globally, and don't seem to have any problems switching between them randomly (but reproducing the history I used to get there is probably impossible by now).
