### ISSUE TITLE
Performance penality of using resources

### ISSUE THREAD

**Issue by peti** [ndmitchell/shake#585]
I have a fairly large build system that mostly downloads data from an internal web service by calling a special-purpose executable with appropriate arguments, i.e. the whole build is essentially a long, long sequence of 

    foo --bar https://example.org/some/arg/123

calls. Because these things put a bit of a strain on the server, I usually run my build with `-j2` to ensure no more than two of those puppies are running at the same time.

Now, at some point I felt that `-j2` is not the right way to do this and instead I wrapped all my calls to that external tool to use `withResource`. Incidentally, this change has *doubled* the time it takes to download all files, because 

a) the generated shake build consumes significant CPU time, certainly far more than before and, more importantly,

b) there is a noticeable delay after a running download process has terminated before the next one starts up.

Now I wonder: is this a known phenomenon? I understand that managing a resource pool must add *some* amount of overhead, but I would have never guessed that those couple of trillion CPU calculations would even be observable compared to the insane slowness of downloading data from a remote web service through an external Unix process, i.e. I'd be prepared for a performance hit of, say 10%, but not 100%!

I dunno ... comments? Thoughts?

**Comment by ndmitchell** [comment]
This is not known, not expected, and when I tweaked my standard Shake benchmarking tool https://github.com/ndmitchell/shake/blob/master/src/Test/Benchmark.hs, which creates a 75 layers of dependencies, each with 75 dependencies on the previous layer, I couldn't find any slowdown. I tried a bunch of permutations, but the closest to what you describe was a resource of quantity 2, where 1 was required to do the write file. I made the action inside the resource take longer with a sleep. I tried higher and lower levels of parallelism. In every case the resources were no slower, usually faster, because they were only limiting parallelism for the part that was resource limited.

So I dunno - can you reproduce this in any way? Can you make a small example that shows it? I'm 64bit Windows GHC 8.2, so I'd like to get something we can both see going slow first.

**Comment by peti** [comment]
OK. This probably means that the performance difference I observed had other causes, which is quite likely since the build is downloading stuff almost all the time, so the total run-time actually comes down to network performance more than to anything else. I experimented a bit and it appears that the `-I0` RTS option remedies high CPU consumption I observed. As for for the speed in which download processes start up, I don't have any hard data to back up my impression that this got slower after introducing resources. That might have been confirmation bias: I saw that progress was slower than I was used to and then went to `htop` to inspect the process list, but what I saw might have been what I wanted to see to confirm my preconceived notion.

Anyway, I'll do more experiments. The build system's structure is unpleasant because I need explicit `forP` parallelism a lot. Also, the target set is extremely dynamic: I start out knowing only one target (a list of registered projects), and once that's build I can derive a list of known packages for each project, and once those exist I can derive a list of supported architectures, and so on and so forth, so the build never arrives in a state where all targets are known. Rather it's continuously updating the target list while running. That's probably somewhat uncommon. I suppose profiling is my friend here. Thank you very much for your efforts.

**Comment by ndmitchell** [comment]
Yep, `-I0` is brutal - if it sees your program is "wasting" all its resources spawning external programs it decides to run the GC repeatedly instead. If you are regularly using `forP`, you might be better off with a Forward build system? See Development.Shake.Forward.

If you do isolate the issue I'm keen to profile it too!
