### ISSUE TITLE
Should file hashes include file size too?

### ISSUE THREAD

**Issue by cartazio** [ndmitchell/shake#597]
It may very well not add much value overall, but it seems like it would easily prevent length extension collision, whether deliberate  security issue or accidental.  And shouldn’t change any code on userland shake client side except maybe the build info cache?

Thoughts? Would this be useful to add / be a welcome contribution?

**Comment by ndmitchell** [comment]
Currently file "hashes" include modtime, length and hash.

* If the modtimes match, files are considered to be equivalent.
* If the lengths don't match, files are considered to be different.
* Otherwise hashes are checked.

So yes, hashes already include size, and it turns out that's really helpful to avoid actually reading the file when the size has changed anyway. See https://github.com/ndmitchell/shake/blob/49f2ea37581d02660b38e7e620d9dc1790c75021/src/Development/Shake/Internal/Rules/File.hs#L59 for the approximate code implementing this.

**Comment by cartazio** [comment]
Oh thx!  I was looking at the wrong modules it seems!
