### ISSUE TITLE
Rules for services

### ISSUE THREAD

**Issue by joneshf** [ndmitchell/shake#615]
At work, we've got a project that consists of a Haskell backend that talks to a postgres database. Currently, we're using docker-compose to run postgres as a persistent service in the background. We're moving to using shake more thoroughly throughout the project. We have the Haskell part integrated with shake already and it's been great!

We started thinking about how/if we might use shake to run postgres as part of the build. For instance, if we have a rule to run the tests and those tests need to hit postgres, we would like to have the test rule `need` something about postgres running. Or, if we have a rule to run the server so you can interact with it from a webpage, we would like to have the server rule `need` something about postgres running.

Is this a wild idea, or does it seem like something in shake's wheelhouse? Maybe we could use an oracle or something that looks at `pg_isready` or something? It's not really clear how we'd control the starting and stopping of the postgres server reliably. Maybe this is too out there. If so, any other ideas?

**Comment by ndmitchell** [comment]
Great that Shake is working well for you :)

I guess the first question I'd ask is what are you aiming for the lifetime postgres database? Do you want to start it when necessary, and then tear it down at the end? If it's running from one run to another, is that good or bad? Does it take a long time to start? For some executions are you hoping it won't be started at all?

**Comment by joneshf** [comment]
Great questions! I think the only real requirement we have is that data can persist between runs; which seems not to be a concern of shake's. Other than that, we're pretty open to whichever approaches make the most sense.

To give a similar feel to the docker-compose stuff it would start once and continue running in the background. Startup is on the order of single-digit seconds, so it's fine if shake starts and stops after each run. Reliability/reproducibility is a bigger value than speed in this case.

I think it'd be really instructive to know how you'd approach each of the alternatives in your questions. Part of what I'm missing about build systems is how to use them to solve process problems. Another part is knowing when to recognize a build system as a good solution to a problem, vs. being excited about build systems.

**Comment by bitc** [comment]
I have a similar situation.

I am using a compiler-like tool. It can be run the usual way from the command line to compile my source code, but the problem is that it takes a long time to start up. So it can also be run as a server, in which case it listens on a socket and accepts commands through the socket (and emits the success result or errors back through the socket).

I wrote my Shake build script such that it checks an environment variable for the port of the socket. If the environment variable isn't set, then it invokes the tool the slow way through the command (which is good for CI environments). But during development I start the server up and set the environment variable so that I get faster builds.

So bringing this back to this issue, it would be cool if there was a way for shake to automatically start the server so that I wouldn't have to go to the trouble of manually remembering to start it myself and set the environment variable. And of course this should be tied into shake's dependency logic, so that shake would only start the server for the first time when something that actually needs it is about to be built (and then it would remain running and be available for subsequent builds)

On the other hand, my current system is simple and overall works well, so it might not be worth it to add lots of additional complexity to shake

**Comment by ndmitchell** [comment]
Looking at the options:

* If you want to start the thing before Shake, and stop it after, you don't have to do that in Shake. Shake is deliberately an EDSL, so you can run whatever code you want before Shake, even code that returns some kind of in-memory handle, and pass it on to Shake as an argument to the rules. Not everything is best solved with a build system, and fortunately Shake is flexible here.

* You almost certainly don't want it part of the build graph, since whether it runs depends on whether the things that depend on it have changed. That's the wrong way round for a build graph.

My approximate suggestion for many situations would be:

```haskell
rules = do
    startCompiler <- newCache $ \() -> do
        ... start the compiler here ...
        runAfter $ ... shut down the compiler here ...

    "*.lang" %> \out -> do
        startCompiler ()
        ... now use the compiler ...
```

It will run the startup at most once per run, only if it's needed, it will start it single-threaded (no race conditions), and it will shut it down properly afterwards. Does that cover all use cases? Seems like a good FAQ.

**Comment by joneshf** [comment]
Oooo, that's a really helpful example!

> * You almost certainly don't want it part of the build graph, since whether it runs depends on whether the things that depend on it have changed. That's the wrong way round for a build graph.

Sorry, I don't really understand this point. Are you suggesting that instead of the build artifacts `need`ing the server, the server should `need` the artifacts?

**Comment by ndmitchell** [comment]
I'm suggesting you can't wire in the build server in the graph at all, since it doesn't make sense for the artefacts to depend on the build server (the build server doesn't know if the artefacts need rebuilding at that point) and it also doesn't make sense for the server to depend on the artefacts, since that doesn't make any sense as a dependency. The above example avoids doing that entirely.

**Comment by ndmitchell** [comment]
I've now added this pattern to the test suite, and consider it the best way to do almost all the problems that were described. I think the right place for this to go as document is on StackOverflow. Either I can ask and answer, or @joneshf can ask the question and I'll flesh out the example and document it more fully - I'm fine either way.

**Comment by joneshf** [comment]
Thanks! This is great. Please feel free to ask and answer. I think you do a great job with those SO Q/As.

For visibility, is this the commit you mean: https://github.com/ndmitchell/shake/commit/ab9e16065fc069726652b10b032a70e2de904a66?

**Comment by ndmitchell** [comment]
Yep, that's the commit.

Asked and answered at https://stackoverflow.com/questions/52815763/using-persistent-services-with-shake

**Comment by joneshf** [comment]
Finally got around to following this approach, but I'm not sure if it's going to work. `runAfter` only seems to run if the build finishes successfully. If there's a problem with the build, it doesn't run any of the cleanup.

Here's a simplified example of what we're doing:

```Haskell
import Development.Shake
import System.Process (interruptProcessGroupOf)

main =
  shakeArgs shakeOptions $ do
    startServer <- newCache $ \() -> do
      Process server <- cmd "python2 -m SimpleHTTPServer"
      runAfter $ do
        putStrLn "shutting down server"
        interruptProcessGroupOf server

    phony "fail" $ do
      startServer ()
      cmd_ "sleep 3"
      fail "Intentionally failing"
```

The `shutting down server` line doesn't run and the python server is still up and running.

It kind of feels like this needs a `bracket` style thing, but it doesn't look like that can be done with `newCache` since it has `Eq` and `Hashable` constraints. Trying to use `bracket` directly in the action doesn't seem to propagate errors either or cleanup successfully (though that's probably because of `interruptProcessGroupOf` more than any thing else). Any other ideas about what we could do?

**Comment by ndmitchell** [comment]
Sorry for missing this follow up question, just happened to glance at it now. Let me know if it's still relevant - you can certainly use an MVar or similar outside of Shake and then wrap all of Shake in a bracket, but it's more work.
