### ISSUE TITLE
More details in progress callback

### ISSUE THREAD

**Issue by bitc** [ndmitchell/shake#638]
It would be cool if the progress callback could add more details:

  - An event for when a command has just started (including an ID of the new command, the target file, and full command line)
  - An event that fires when a command emits some stdout or stderr (tagged with the ID of the command)
  - An event for when a command has completed execution (the ID of the command that just finished, including the exit code)
  - Similar events to the above for "traced" calls
  - Events for all putNormal, putLoud, putQuiet
  - Any others?

This could be used to implement an alternative UI for running shake. One idea I have is an interactive ncurses UI that shows you the currently running jobs, with a realtime timer next to each one showing how long it's been running, and the ability to click a job to view the full command line, etc... Also a web UI could be created that streams the events through a websocket and displays a javascript/CSS UI similar to the above description (would be awesome for CI servers)

Of course these UIs would not be built into shake itself, they would be separate libraries that hook into the enhanced progress callback.

**Comment by ndmitchell** [comment]
Seems thoroughly plausible - so you turn Shake into a SAX based event streams of what it's doing. If we did that, I'd want to take the existing UI out of the "core" and put it still inside the Shake package but not wired in to the internals. I think a more compressed view (ala Buck, which is what I've used elsewhere, and seems approximately what you are describing) is a good thing.

**Comment by ndmitchell** [comment]
I added `shakeTrace` which gives you the start/stop of `traced`, and since `cmd` calls `traced` you can get info that way. You already have shakeOutput to get messages like putNormal etc. With all that combined, you can write something fancier on top, and I have done so - see https://asciinema.org/a/228101. That is almost entirely outside of the core of Shake (the only integration point is the argument flag).

I'm closing this as all the low hanging fruit is done, and you can do something. If you put together a GUI using what's here, I'd love to see it, and we can see if there is anything in particular that might be worth adding.

**Comment by bitc** [comment]
That asciinema link doesn't seem to be working :frowning_face:

**Comment by ndmitchell** [comment]
https://asciinema.org/a/228128 - sorry, I uploaded a better version, but forgot I'd pasted it to you
