### ISSUE TITLE
Allow to disable --compact

### ISSUE THREAD

**Issue by pepeiborra** [ndmitchell/shake#672]
`--compact` is pretty good but it doesn't work in non terminals, such as CI. It's also not possible to set it programmatically. 

We could use a way to disable it from command line (e.g. `--no-compact`), or additional smarts that self-disable it when not in a terminal device ([or when the terminal device is DUMB](http://hackage.haskell.org/package/ansi-terminal-0.9/docs/src/System.Console.ANSI.Unix.html#hSupportsANSI)).

**Comment by pepeiborra** [comment]
I'm happy to implement this if you let me know what is your preferred option

**Comment by ndmitchell** [comment]
Since `--compact` has to be added explicitly isn't it easier to just not set it on CI?

I still don't have a good idea of what the API should be for compact. It's a bit cross cutting - it prods a few fields in ShakeOptions to do its job. Making it not turn on when the terminal device is dumb is one way - you could have `--compact=auto` to mean only turn on if terminal is not dumb?

Not that Compact already has an idea if it's going to work or not, see https://github.com/ndmitchell/shake/blob/master/src/Development/Shake/Internal/CompactUI.hs#L64
