### ISSUE TITLE
Shake manual page use need makefile dependencies but probably ment needed makefile dependencies

### ISSUE THREAD

**Issue by Neppord** [ndmitchell/shake#696]
Hi!

If I understood the documentation correctly the needed variant should be used if the dependencies already was used, which I think is true in the example.

**Comment by ndmitchell** [comment]
Thanks for the bug report, and thanks @dwijnand for the PR. It was actually intentional the use of `needMakefileDependencies`. The logic being that in the user manual I am trying to introduce as few concepts as possible, and `need` is the "simplest" form of dependency. The idea was that then people would progress to `needed` only later on. However, that does mean the central example in the user manual isn't following best practices. Given two of you thought this was a good idea I'll change it.

**Comment by dwijnand** [comment]
I can see the argument either way.  I don't feel strongly about it - I submitted the PR because I felt @Neppord's POV made sense and it was an easy ramp-up change.  But I don't mind if you were to prefer the status quo and reject my PR. (JFYI)

**Comment by Neppord** [comment]
Since ’needMakefileDependencies’ is a special case of ’need’ I don't feel that using ’needed’ confuses more. And I think it's better to be correct in the example then trying to make it easier, when we still use other advanced features.

**Comment by ndmitchell** [comment]
Thanks for your viewpoint. Let's merge then!
