### ISSUE TITLE
How to do phony rules e.g clean in forward mode

### ISSUE THREAD

**Issue by locallycompact** [ndmitchell/shake#750]
Hi, is there a way to do this? I like forward mode but I also like being able to do `shake clean`.

**Comment by ndmitchell** [comment]
Phony can't work because phony relies on going backwards to find names, forward specifically doesn't do that. It would be possible to add a something akin to `shakeArgsWith` for forward, e.g.:

```
shakeArgsForwardWith :: ShakeOptions -> [OptDescr (Either String a)] -> ([a] -> [String] -> Action ()) -> IO ()
```

Then you could capture the arguments e.g. clean from the closure, something like:

```
shakeArgsForwardWith defaultOptions [] $ \_ xs -> if "clean" `elem` xs then clean else build
```

Would that solve your needs?

**Comment by locallycompact** [comment]
Hi, thanks.

I ended up just switching to backwards mode.
