### ISSUE TITLE
Performance consequences of the ordering in `localDepends`/`depends`

### ISSUE THREAD

**Issue by afranchuk** [ndmitchell/shake#779]
I've been reading the code but can't quite seem to find the purpose of the ordering that is retained in `localDepends` (in `Local`) and consequently `depends` (in `Result`). Is there a real need for this? I ask because I have a program using `shake` which ends up with a fairly large (and more importantly, fairly deep) tree of dependencies. `mergeDependsRev` (introduced in https://github.com/ndmitchell/shake/commit/991391bf691a6ca3a99ab991716526b7dd91412e) wreaks havoc with this, causing enormous memory usage and eventual crashing due to the system OOM killer). I have a rough back-of-the-napkin figure indicating that with deep and bottom-heavy dependency trees, that becomes a large exponential runtime (and memory usage due to list manipulations). A large part of the runtime hit is also due to GC, based on profiling. The lists could probably be changed to something more efficient in terms of memory use, but I wonder whether they can't just be some sort of set? That would obviate `nubDepends` if it were possible. There was only one place in the code that seemed like the dependency order really mattered: https://github.com/ndmitchell/shake/blob/680713dbe6e3c9075735b1ffe8861c180a9aaeea/src/Development/Shake/Internal/Core/Action.hs#L457. But I think that could be refactored to work in a different way if sets were used.

So just curious what the reasoning behind the ordering is. I was able to revert to v0.17.6 to avoid the problem (now it completes immediately rather than hanging at the end of the build!).

**Comment by ndmitchell** [comment]
Ouch - sorry to hear about such a regression. I wasn't expecting that area of the code to be a hot-spot at all. Do you use `parallel` or `forP` a lot? In a deeply nested way? It would be good to have something that approximates the essence of what you do, so I can add a test case for it.

The depends are really a list of sets. So you must depend on everything in the first item of the list before you depend on anything in the second element, but you can check all the elements in the first in parallel. The more things you can drag into the earlier in the list the more parallelism you get when checking.

I imagine we are suffering because we keep building up lists and merging them repeatedly. The solution is to hold a data structure that can be constructed in O(1), and then flatten it at the end. I'll give that a go.

**Comment by ndmitchell** [comment]
I've pushed changes which accumulate the dependencies in O(1) time operations, then flatten them once at the end, where the total cost can be amortised. There's one potentially non-linear operation in there with parallelism, which I worry you might hit, but I'd be keen to get your feedback - its probably better than both the last release and 0.17.6. Are you able to try HEAD?

**Comment by afranchuk** [comment]
Thanks @ndmitchell, I'll see if I can try master. If it ends up being too much effort (I was previously on 0.17 before), I'll try cherry-picking those changes to see the difference.

**Comment by ndmitchell** [comment]
Hmm. Do you use `batch`? That also goes through this code path.

**Comment by afranchuk** [comment]
No, I don't. I _only_ use `need` and `apply`. But I was able to use master and can confirm that your changes fixed the issue, so thank you for your quick action!

**Comment by ndmitchell** [comment]
Great it fixed it. But I've got not the slightest idea why this code was a hot spot. I guess we do call this code once per run anyway... Either way, definitely an improvement, and glad it helped your code. I'll ship a release in a few days - just waiting for confirmation another bug is fixed.
